### ISSUE TITLE
Question: Are there any plans to support OpenTofu?

### ISSUE THREAD

**Issue by matheuscscp** [weaveworks/tf-controller#1016]
Hi tf-controller team,

Are there any plans to support OpenTofu? Happy to contribute in any form.

Kind regards,

**Comment by chanwit** [comment]
Hi @matheuscscp 
 
Thank you so much for bringing this up.
We've been busy tackling all things Terraform, and it's certainly kept our hands full.

Regarding OpenTofu, your offer to contribute is much appreciated. Please feel free to get involved.

**Comment by scottrigby** [comment]
@LappleApple @chanwit was this actually completed?

**Comment by LappleApple** [comment]
@scottrigby The issue is scoped to the question, which is answered above.
