### ISSUE TITLE
Support for tf security scanning

### ISSUE THREAD

**Issue by calumgoodchild** [weaveworks/tf-controller#1031]
Does this tool support integration with security scanning tools like bridgecrew? So once the tf plan has run, we can check it against security policies to make sure nothing vulnerable gets deployed?

I understand we can do this at the repo level, but it would be good have a last line of defence when deploying.

**Comment by chanwit** [comment]
Yes, we have an implementation of post-plan Web hooks for validating plans with, for example, our open-source Weave Policy Engine.

I'll find the integration docs and get back to you.

**Comment by Nalum** [comment]
Here is the docs link https://github.com/weaveworks/tf-controller/blob/main/docs/use_tf_controller/with_external_webhooks.md?plain=1

Will close this, please re-open/create ticket if needed
