### ISSUE TITLE
Helm: Access denied for GitRepository after upgrade to 0.16.rc3 from 0.15.1

### ISSUE THREAD

**Issue by mtandersson** [weaveworks/tf-controller#1052]
I am getting the following in the logs:

"msg":"Source 'GitRepository/flux-system/flux-system' access denied","controller":"terraform","controllerGroup":"infra.contrib.fluxcd.io","controllerKind":"
Terraform","Terraform":

The clusterrole for that section tf-manager-role looks the same.

Rolling back to 0.15.1 and it works again.

**Comment by chanwit** [comment]
We have recently introduced the Lockdown mode, which prevents cross-namespace reference by default for security purpose, in v0.16.0-rc.

cc @squaremo for the tech details

**Comment by mtandersson** [comment]
Thanks for the reply. Found it in the release notes. Adding the flag `--allow-cross-namespace-refs=true` will get the old behavior.

**Comment by artem-nefedov** [comment]
This was confusing, because changelog only mentions Secrets and ConfigMaps, but in reality it affects source objects too

**Comment by kaden-l-nelson** [comment]
> We have recently introduced the Lockdown mode, which prevents cross-namespace reference by default for security purpose, in v0.16.0-rc.
> 
> cc [@squaremo](https://github.com/squaremo) for the tech details

For future readers - is there a link that references what the recommended configuration is for using GitRepositories?
