### ISSUE TITLE
import initial tfstate with a secret

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#11]
We currently could do the following to import a TFSTATE for a specify Terraform object.

```shell
gzip terraform.tfstate

NAME=tf-controller-ng-cc5a1ac4
kubectl create secret \
  generic tfstate-default-${NAME} \
  --from-file=tfstate=terraform.tfstate.gz \
  --dry-run=client -o=yaml \
  yq e '.metadata.annotations["encoding"]="gzip"' - > tfstate-default-${NAME}.yaml
  
kubectl apply -f tfstate-default-${NAME}.yaml
```

Need a good UX / design / approach to tackle this feature.

**Comment by chanwit** [comment]
A CLI for this would be nice to have

**Comment by yitsushi** [comment]
Closing this issue:
We have https://github.com/weaveworks/tf-controller/issues/423 to implement an `import` command as @chanwit's [comment](https://github.com/weaveworks/tf-controller/issues/11#issuecomment-1019521093) suggests. I think that issue covers this.
