### ISSUE TITLE
How to import manually created existing Terraform resources into Weave TF Controller

### ISSUE THREAD

**Issue by Anoop-P-Hegde** [weaveworks/tf-controller#1108]

**Comment by LappleApple** [comment]
@Anoop-P-Hegde Thanks for checking out TF-Controller. If you've not read our docs, please check out this page: https://weaveworks.github.io/tf-controller/getting_started/. 

If you still have questions, please join the #tf-controller channel in the Weave Users Slack and we can help there: https://weave-community.slack.com/.
