### ISSUE TITLE
Implement the `CreateWorkspaceBlob` gRPC function to create, compress, encrypt, and retrieve Workspace BLOBs from the tf-runner.

### ISSUE THREAD

**Issue by yiannistri** [weaveworks/tf-controller#1120]
From https://github.com/weaveworks/tf-controller/discussions/911

> Creating Workspace BLOB: The TF-Controller invokes a new gRPC function named "CreateWorkspaceBlob".
> The content of the Workspace file system is compressed using tar and gzip to produce the Workspace BLOB.
> The TF-Controller retrieves this BLOB as a byte array via the return value of the CreateWorkspaceBlob gRPC function.

Creation, compression and encryption process are done in tf-runner.

**Comment by chanwit** [comment]
Not that dir, but the whole terraform dir that is extracted.

Basically the idea is to keep everything after code generation (vars, secrets, configmap) as a tar gz blob.
