### ISSUE TITLE
GitHub page down, affecting helm chart

### ISSUE THREAD

**Issue by larivierec** [weaveworks/tf-controller#1165]
The GitHub page is currently returning a 404.
As a result, we can't download the helm chart anymore.

Is there anyway this can be fixed?

Thanks

**Comment by katherine-albany** [comment]
`helm repo add tf-controller https://weaveworks.github.io/tf-controller/`

`Error: looks like "https://weaveworks.github.io/tf-controller/" is not a valid chart repository or cannot be reached: failed to fetch https://weaveworks.github.io/tf-controller/index.yaml : 404 Not Found`

**Comment by nkokubo318** [comment]
The download error with the Helm chart has been resolved, but it seems that the GitHub page is still not accessible.

**Comment by larivierec** [comment]
ok, i'll close my ticket as it was only regards to the helm chart.
thanks whoever fixed this
