### ISSUE TITLE
Helm chart version v0.16.0-rc.3 not available

### ISSUE THREAD

**Issue by tao-zhang-shell** [weaveworks/tf-controller#1173]
The latest chart v0.16.0-rc.3 is not available.

Although I can change `image.tag` to v0.16-rc.3 for app version, `allowCrossNamespaceRefs` is only added to v0.16-rc.3 and is not available in chart version v0.15.1.

Then I'm not able to use the feature of `allowCrossNamespaceRefs`.

Can you please release a new chart version `v0.16-rc.3`?

<img width="938" alt="Screenshot 2024-01-02 at 17 01 50" src="https://github.com/weaveworks/tf-controller/assets/102809881/941ee6fd-f139-45bc-9b04-55759ded8f27">

**Comment by dwalker-sabiogroup** [comment]
`0.15.1` is the latest stable chart.  If you want to use non-stable charts you will need to use the `--devel` flag

```shell
helm search repo tf-controller
NAME                            CHART VERSION   APP VERSION     DESCRIPTION                                       
weaveworks/tf-controller        0.15.1          v0.15.1         The Helm chart for Weave GitOps Terraform Contr...

helm search repo tf-controller --devel
NAME                            CHART VERSION   APP VERSION     DESCRIPTION                                       
weaveworks/tf-controller        0.16.0-rc.3     v0.16.0-rc.3    The Helm chart for Weave GitOps Terraform Contr...
```

**Comment by tao-zhang-shell** [comment]
@dwalker-sabiogroup Thank you! Yes, if I install with `--version v0.16.0-rc.3`, it works!
