### ISSUE TITLE
Provide easy install pathway for `tfctl`

### ISSUE THREAD

**Issue by phoban01** [weaveworks/tf-controller#197]
Currently installing the `tfctl` cli requires cloning the repo and executing `make install-cli`. 

We should distribute binaries using GitHub releases, we could look at using [GoReleaser](https://goreleaser.com/) for this or can simply update the release action.

**Comment by chanwit** [comment]
Please also consider

`brew install weaveworks/tap/tfctl` too.

We can also have `tf-controller/tap/tfctl` if we cannot do the former.

**Comment by phoban01** [comment]
GoReleaser can create brew releases so let's go with that.
