### ISSUE TITLE
Error "must be no more than 63 characters"

### ISSUE THREAD

**Issue by Nalum** [weaveworks/tf-controller#204]
I'm getting the following error when I try to have my Terraform run:

```
error saving plan secret: rpc error: code = Unknown desc = error recording plan status: Secret "tfplan-default-testing" is invalid: metadata.labels: Invalid value: "plan-1a4dc9d874988bb51646864196d008f40816bb94c8ca54d3426c0c183f262702": must be no more than 63 characters
```

The Terraform script is very simple, just 1 output, for testing purposes:

```hcl
output "testing" {
  value = "Hello World"
}
```

**Comment by chanwit** [comment]
Thank you for reporting this, Luke.

Definitely a bug.
Is this something from other kind of sources?

**Comment by Nalum** [comment]
@chanwit the source that is holding the terraform script shares a few other flux resources but also has 8 helm charts.

**Comment by o6uoq** [comment]
This is due to the Kubernetes character limit for labels:

> Valid label value:
> - must be 63 characters or less (can be empty)

Reference: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/

**Comment by o6uoq** [comment]
**FWIW**

As per [RFC1123](https://datatracker.ietf.org/doc/html/rfc1123):

> The DNS defines domain name syntax very generally -- a string of labels each containing up to 63 8-bit octets, separated by dots, and with a maximum total of 255 octets.
> 
> Host software MUST handle host names of up to 63 characters and SHOULD handle host names of up to 255 characters.

Related: [What is the maximum length of a DNS name?](https://stackoverflow.com/questions/32290167/what-is-the-maximum-length-of-a-dns-name)

[Kubernetes PR](https://github.com/kubernetes/kubernetes/pull/1830) adding [RFC952](https://datatracker.ietf.org/doc/html/rfc952) (which is updated by [RFC1123](https://datatracker.ietf.org/doc/html/rfc1123)(https://datatracker.ietf.org/doc/html/rfc952) validation to labels.

[Is It DNS?](https://isitdns.com/)

**Comment by chanwit** [comment]
plan-${revision} is used as a guard rail to double check that we pick the right plan to process.
It could be possible to move it to annotations instead of labels.
