### ISSUE TITLE
Option for Pull Request on plan

### ISSUE THREAD

**Issue by steveww** [weaveworks/tf-controller#216]
Currently when not using `auto` the plan commit is show in the status. This plan commit must then be put into the manifest and pushed. This workflow could be greatly improved if the tf-controller could create a pull request with this change against the management repo. In a similar way to how Flux image automation works.

**Comment by chanwit** [comment]
Thank you for the feature idea, @steveww.

**Comment by chanwit** [comment]
@phoban01 @tomhuang12 
it would be great to start a discussion here around Git providers / PR integrations, please.

**Comment by tomhuang12** [comment]
We can reuse a lot of the code from image automation controller for committing and pushing: https://github.com/fluxcd/image-automation-controller/blob/cd9eaffefc3072df552790e8e1649762e0ef9922/controllers/imageupdateautomation_controller.go#L368-L392

**Comment by steveww** [comment]
Rather than double up on the code, how about the image automation controller exposing the PR functionality as an API? Careful consideration of security is essential.

**Comment by LappleApple** [comment]
Closing due to issue age and other priorities coming before it.
