### ISSUE TITLE
Recreate Runner Pod

### ISSUE THREAD

**Issue by Nalum** [weaveworks/tf-controller#220]
If the `tf-runner` pod is deleted from the namespace the `tf-controller` does not recreate it.

I've hit this issue but thought it'd messed up something in my setup, hit it again today and had to delete the `tf-controller` which then recreated the `tf-runner`.

**Comment by tomhuang12** [comment]
@Nalum thanks for the report. Could you provide a bit more details to reproduce the issue please? When did the `tf-runner` pod get deleted?

**Comment by Nalum** [comment]
I think it was within a few minutes of creation, no more than 30 minutes after, if I recall correctly.

**Comment by Nalum** [comment]
In #226 I've noted `tf-runner` pods not being updated when the `tf-runner` version is updated.

While trying this I had 2 runner pods going. I decided to delete one of them to see if the `tf-controller` would recreate it, but it didn't. I then deleted the `tf-controller` pod to see if it would recreate it on a new start up but it hasn't.

A cut of the logs from after the new start up, it sees that there is an existing `tf-runner` but when I delete one the `tf-controller` doesn't seem to take notice of that:

```
{"level":"info","ts":"2022-05-11T14:23:08.708Z","logger":"controller.terraform","msg":"Starting workers","reconciler group":"infra.contrib.fluxcd.io","reconciler kind":"Terraform","worker count":1}
{"level":"info","ts":"2022-05-11T14:23:08.708Z","logger":"cert-rotation","msg":"no CA or server cert refresh needed"}
{"level":"info","ts":"2022-05-11T14:23:11.183Z","logger":"controller.terraform","msg":"runner is running","reconciler group":"infra.contrib.fluxcd.io","reconciler kind":"Terraform","name":"custom-khchecks","namespace":"flux-system"}
```

**Comment by Nalum** [comment]
This issue is potentially not real and was happening due to Proxy setup. Will close it for now and we can re-open if needed.
