### ISSUE TITLE
runnerPodTemplate missing in the Helm chart template

### ISSUE THREAD

**Issue by Sbou** [weaveworks/tf-controller#225]
Hello,

The new `runnerPodTemplate` field has been updated to the **config/crd/bases/infra.contrib.fluxcd.io_terraforms.yaml** file but not in the CRDS existing in the Helm chart (**charts/tf-controller/templates/crds.yaml**).

Thank you

**Comment by chanwit** [comment]
We corrected it in chart version v0.2.9.
