### ISSUE TITLE
Support destroy action for a Terraform object not attaching to a Source

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#246]
A Terraform object is not guaranteed to permanently attach to a Source. In some scenarios, the Source is deleted before deleting the Terraform object.

Fortunately, `terraform destroy` can be run against a Terraform state to delete all of its resources.
In order to do so, we will improve the semantic of `destroyOnDeletion` to destroy directly with the state file, without `planning` or `applying`.

**Comment by LappleApple** [comment]
Closing in favor of the more recent, prioritized, and detailed https://github.com/weaveworks/tf-controller/issues/632.
