### ISSUE TITLE
A capability to specify pod and container spec for the runner (was: Test new pod security on OpenShift)

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#261]

**Comment by hcecille** [comment]
Hello @chanwit,
do you have any updates on this issue ?

I'm trying to use tf-controller (v0.15.1) on Openshift (4.11) with Flux (v2.0.1).
I have a problem on tf-runner pod with securityContext, I've checked the documentation to customize my runner pods: https://weaveworks.github.io/tf-controller/use_tf_controller/to_provision_resources_with_customized_Runner_Pods/ but i do not see the field securityContext on the specs.

My error message:
spec.containers[0].securityContext.runAsUser: Invalid value: 65532: must be in the ranges: [1007690000, 1007699999], pod.metadata.annotations[container.seccom...

Thanks for your answer.

**Comment by chanwit** [comment]
Thank you for input @hcecille 
@luizbafilho is working on a PR regarding integration of PodSpec and/or ContainerSpec into the runner pod template.

**Comment by chanwit** [comment]
@luizbafilho is the right person to give you ETA.

**Comment by LappleApple** [comment]
This has been solved by #786
