### ISSUE TITLE
make the tf-controller compatible with other CD tools

### ISSUE THREAD

**Issue by prune998** [weaveworks/tf-controller#284]
Just asking the question here, as I know this project is tied to Flux right now.
Do you see any way that we could use that with any other CD tooling like ArgoCD ? What would be the effort needed to open it ? 

Thanks.

**Comment by chanwit** [comment]
Hi @prune998 

It's actually not very tied to Flux in a sense as it's working already on Argo CD via the Flux Subsystem for Argo. 

Here's the tutorial:
https://flux-subsystem-argo.github.io/website/tutorials/terraform/

**Comment by prune998** [comment]
Thats is super great ! Thanks @chanwit... I was reading the docs but never went down to the tutorials ! 
Thanks !
