### ISSUE TITLE
Make alert for drift detection work

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#295]

**Comment by chanwit** [comment]
We got drift detection work via the Notification controller. The Flux's doc will include instructions how to set the notification controller up to support Terraform soon.

Screenshot:
![image](https://user-images.githubusercontent.com/10666/187060366-fe150063-e96d-4a09-9c36-b3a94fe98661.png)

**Comment by pojbik** [comment]
Hi, do we have any mechanism to monitor events from Terraform CRs ?
