### ISSUE TITLE
Hanging deletion after creating Terraform resource in namespace without ServiceAccount

### ISSUE THREAD

**Issue by artem-nefedov** [weaveworks/tf-controller#300]
When you create a Terraform resource in a namespace without `tf-runner` ServiceAccount, attempting to delete it will hang indefinitely. You have to manually remove finalizer "finalizers.tf.contrib.fluxcd.io" to unblock deletion.

Meanwhile, controller will continuously report the same logs:

```
{"level":"error","ts":"2022-08-16T14:54:56.381Z","logger":"controller.terraform","msg":"unable to lookup or create runner","reconciler group":"infra.contrib.fluxcd.io","reconciler kind":"Terraform","name":"vpc","namespace":"default","error":"pods \"vpc-tf-runner\" is forbidden: error looking up service account default/tf-runner: serviceaccount \"tf-runner\" not found"}
{"level":"error","ts":"2022-08-16T14:54:56.382Z","logger":"controller.terraform","msg":"Reconciler error","reconciler group":"infra.contrib.fluxcd.io","reconciler kind":"Terraform","name":"vpc","namespace":"default","error":"pods \"vpc-tf-runner\" is forbidden: error looking up service account default/tf-runner: serviceaccount \"tf-runner\" not found"}
```

Controller version: `v0.12.0-rc.1`

`interval: 1m0s` (in case that is important)

**Comment by aristapimenta** [comment]
and how is the `tf-runner` SA supposed to be created in other namespaces which are not `flux-system`? are `Terraform` objects only supposed to be created inside the `flux-system` namespace?

**Comment by artem-nefedov** [comment]
@chanwit FYI Besides this, I've encountered other scenarios where it becomes impossible to remove Terraform resource without deleting finalizers if something goes wrong (e.g. if path is specified incorrectly). This is a huge problem, especially if used in gitops approach, because it makes making further changes impossible. Not only that, in some cases it will even repeatedly create new runner pods, even though Terraform resource itself is in deleting state.

**Comment by aristapimenta** [comment]
> and how is the `tf-runner` SA supposed to be created in other namespaces which are not `flux-system`? are `Terraform` objects only supposed to be created inside the `flux-system` namespace?

looks like the right way is using the helm value `runner.serviceAccount.allowedNamespaces` in the tf-controller `HelmRelease`

**Comment by LappleApple** [comment]
Hi all: Still experiencing this issue?

**Comment by LappleApple** [comment]
@artem-nefedov @aristapimenta If you're still experiencing issues, please comment on https://github.com/weaveworks/tf-controller/issues/1017 as we'll be tracking that issue and now closing this one.
