### ISSUE TITLE
Terraform not having status initialized breaks the Flux Kustomization health checks behavior

### ISSUE THREAD

**Issue by artem-nefedov** [weaveworks/tf-controller#302]
# Description

When applying Terraform objects using flux Kustomization created with `--wait` flag (`wait: true` in the manifest), it is expected that Kustomization will only become "ready" after all Terraform resources in it reconcile successfully.

However, what actually happens is that Kustomization becomes ready immediately upon creation, and then changes state from "ready" to "in progress" after a small delay. This causes a multitude of problems, one of which is it breaks Kustomization dependencies (E.g. you have a second Kustomization that needs to be applied only when first one is fully reconciled, so you add the first one into `dependsOn` field. But because the first one becomes ready immediately, second one will also be incorrectly applied right away.).

My assumption of why it happens is because Terraform resource initially doesn't have `status.conditions` after creation (they get added later), so kustomization-controller assumes that because of that it shouldn't wait for that resource.

I have thought of a hacky workaround where, instead of using `wait: true`, I can use `healthCheck` field and make it look at both Terraform resource and output Secret, but I would want to avoid such hacks if possible.

# Environment

tf-controller version: `v0.12.0-rc.1`
kustomize-controller version: `v0.27.0`

**Comment by chanwit** [comment]
Yes, we also observed that behavior but hadn't had a chance to capture it as a bug.

Thank you for reporting this @artem-nefedov!

**Comment by artem-nefedov** [comment]
I tested `v0.12.0-rc.2` with the fix and I still see this issue.

To reproduce, just apply a kustomization using flux cli with `--wait` flag and `--path` pointing to a directory with a `Terraform` object

**Comment by chanwit** [comment]
I re-arranged the logic to make the status happen sooner, but if it didn't fix your issue, maybe I had to take a look at other parts of the ready status too.

**Comment by artem-nefedov** [comment]
@chanwit It's really easy to reproduce, you can test it as I described above. Expected behavior when creating Kustomization with `--wait` is that it will return only after all child resources are ready, but here you will see that it returns immediately.

**Comment by chanwit** [comment]
Thanks @artem-nefedov 
I should have done that.

The problem seems to be hiding inside other stages of the workflow too.
