### ISSUE TITLE
Invalid rootfs pulling the image

### ISSUE THREAD

**Issue by cakriwut** [weaveworks/tf-controller#307]
Hi team,

I run 
```
docker pull ghcr.io/weaveworks/charts/tf-controller:0.3.9
```

But it gives me error __invalid rootfs in image configuration__.

I am using this
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal

My docker version
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.2
 Git commit:        20.10.12-0ubuntu2~20.04.1
 Built:             Wed Apr  6 02:14:38 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

Is there any guidance?

**Comment by Nalum** [comment]
I think this is an OCI Helm Chart, you would need to pull it using helm as follows: `HELM_EXPERIMENTAL_OCI=1 helm pull oci://ghcr.io/weaveworks/charts/tf-controller --version 0.3.9`

However it looks like it's not been packaged correctly, @chanwit thoughts on this? I might be complete wrong here as I've not looked at this before.

```
❯ HELM_EXPERIMENTAL_OCI=1 helm pull oci://ghcr.io/weaveworks/charts/tf-controller --version 0.3.9
0.3.9: Pulling from ghcr.io/weaveworks/charts/tf-controller
Error: manifest does not contain a layer with mediatype application/tar+gzip
```

**Comment by Nalum** [comment]
Ah looks like the error I have is due to a change in the Helm OCI manifest, I'm running helm `v3.6.1` updating to the latest version has worked:

```
❯ HELM_EXPERIMENTAL_OCI=1 helm pull oci://ghcr.io/weaveworks/charts/tf-controller --version 0.3.9
Pulled: ghcr.io/weaveworks/charts/tf-controller:0.3.9
Digest: sha256:8460709ba0ecd4cf1f63d14aeba803c893e66e848dd40c214008eb66fd54b5fb

❯ ls -lah tf-controller-0.3.9.tgz
-rw-r--r-- 1 nalum nalum  11K Aug 19 12:11 tf-controller-0.3.9.tgz
```

**Comment by chanwit** [comment]
Hi @cakriwut 

Like @Nalum suggested, it's not for the `docker` command but for being consumed by Helm or Flux's HelmController.

**Comment by cakriwut** [comment]
Hi @chanwit / @Nalum ,

Thanks for the response. 
Unfortunatelly, for this issue I didnt do helm install - I only tried to run docker pull based on the instruction in the Release page. 

I can do helm install from this repo - https://weaveworks.github.io/tf-controller/ , successfully.
The helm install latest tf-runner and tf-controller **v0.12.0-rc.1** , unfortunatelly this image always give me this error

```
{"level":"info","ts":"2022-08-19T13:55:25.865Z","logger":"controller.terraform","msg":"Starting EventSource","reconciler group":"infra.contrib.fluxcd.io","reconciler kind":"Terraform","source":"kind source: *v1alpha1.Terraform"}
{"level":"info","ts":"2022-08-19T13:55:25.865Z","logger":"controller.terraform","msg":"Starting EventSource","reconciler group":"infra.contrib.fluxcd.io","reconciler kind":"Terraform","source":"kind source: *v1beta2.GitRepository"}
{"level":"info","ts":"2022-08-19T13:55:25.865Z","logger":"controller.terraform","msg":"Starting EventSource","reconciler group":"infra.contrib.fluxcd.io","reconciler kind":"Terraform","source":"kind source: *v1beta2.Bucket"}
{"level":"info","ts":"2022-08-19T13:55:25.865Z","logger":"cert-rotation","msg":"starting cert rotator controller"}
{"level":"info","ts":"2022-08-19T13:55:25.865Z","logger":"controller.terraform","msg":"Starting EventSource","reconciler group":"infra.contrib.fluxcd.io","reconciler kind":"Terraform","source":"kind source: *v1beta2.OCIRepository"}
{"level":"info","ts":"2022-08-19T13:55:25.865Z","logger":"controller.terraform","msg":"Starting Controller","reconciler group":"infra.contrib.fluxcd.io","reconciler kind":"Terraform"}
{"level":"error","ts":"2022-08-19T13:55:25.900Z","logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"OCIRepository.source.toolkit.fluxcd.io","error":"no matches for kind \"OCIRepository\" in version \"source.toolkit.fluxcd.io/v1beta2\""}
{"level":"error","ts":"2022-08-19T13:55:36.003Z","logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"OCIRepository.source.toolkit.fluxcd.io","error":"no matches for kind \"OCIRepository\" in version \"source.toolkit.fluxcd.io/v1beta2\""}
```

This error is starting from v0.11.0. - and tf-controller will not start tf-runner.
If I use the v0.10.1, tf-controller is healty and it starts the tf-runner.

That where I started to directly pull using docker.

Am I missing anything?

**Comment by chanwit** [comment]
You just need Flux version v0.32.0 for v0.12.0-rc.1.

**Comment by cakriwut** [comment]
Thanks. Confirmed needs Flux version v0.32.0
