### ISSUE TITLE
Implement "secure by default" in TF Controller

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#324]
The "lockdown" mode would be enabled when passing `--no-cross-namespace-refs` to the controller.
In this mode, TF-controller does not allow a Terrafrom CR to refer to Sources that live outside its namespace.

 - [x] #782 ADR saying we'll deny corss-namespace refs by default 
 - [x] #676 Support --no-cross-namespace-refs in branch-planner
 - [x] Extend cross-namespace-refs denial to refs in config (per https://github.com/weaveworks/tf-controller/pull/676#pullrequestreview-1547396551)
 - [x] #840
 - [x] #824 
 - [x] #931

**Comment by chanwit** [comment]
ping @squaremo 
I've just found the root ticket for the lockdown mode.

**Comment by squaremo** [comment]
All items completed!
