### ISSUE TITLE
Update makefile as it is failing to install required binaries for Go v1.18+

### ISSUE THREAD

**Issue by tomhuang12** [weaveworks/tf-controller#328]
`go get` no longer installs the binaries: https://go.dev/doc/go-get-install-deprecation.

I think we can add something so that it runs `go get` for v1.17 and lower and `go install` for v1.18+.

**Comment by Nalum** [comment]
Is it worth having a build container that runs all the make targets? That way the versions are in control and not relying on other peoples systems.

**Comment by tomhuang12** [comment]
Hmm yeah that could be useful. However, if the user want to run commands not in a make target, they would run into a similar issue if version mismatch. 
I think this is the only obstacle I see people are facing when getting started to contribute? I could simply change `go get` to `go install` since GO 1.16 already supports `go install`.

**Comment by bivas** [comment]
@Nalum running make targets in a container might break CI/CD flows to require Docker service in build servers (and even a bigger issue when the CI runners run as container themselves)

**Comment by Nalum** [comment]
We could set it up in such a way that that wouldn't be the case. But just a thought and I can see it over complicating things

**Comment by LappleApple** [comment]
Closing due to age and lack of action.
