### ISSUE TITLE
Refactor the architecture to be A Flux Extension Runtime

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#329]
We have been using the current architecture for a while, and it seems to have many good properties.
For example,

- Multi-tenancy by default
- gRPC-based mTLS communication between controller and runner 
- Scalable (~1,500 concurrencies so far)

This architecture should be refactored to be a reusable Golang module so that we can leverage it to create other Flux extensions.

**Comment by LappleApple** [comment]
After talking to @squaremo and @yiannistri: Creating a library out of TF-Controller would be a nice thing to do, but who is asking for this? I propose we close in light of other pressing needs involving stability/enterprise readiness and customer needs.
