### ISSUE TITLE
Update TF spec from varsFrom to valuesFrom to match Flux HelmRelease spec

### ISSUE THREAD

**Issue by steve-fraser** [weaveworks/tf-controller#341]
Update TF spec from varsFrom to valuesFrom to match Flux HelmRelease spec

**Comment by chanwit** [comment]
While Helm has the semantics of `values`, there is no such semantics in the Terraform world.
Terraform has the concept of `var` blocks. That's why we designed `varsFrom` to support them.

**Comment by tomhuang12** [comment]
@steve-fraser hope Chanwit's answer answers your question. Closing this.
