### ISSUE TITLE
tfctl Error: no Auth Provider found for name "oidc"

### ISSUE THREAD

**Issue by imathu** [weaveworks/tf-controller#357]
using the latest tfctl build  tfctl_Darwin_arm64 on an OSX M1 raises the following error:

❯ ./tfctl version -n <some-namespace>              
Error: no Auth Provider found for name "oidc"
Error: no Auth Provider found for name "oidc"

Fix:
If I include the following import in cmd/tfctl/main.go and rebuild the tfctl command, it works:
_ "k8s.io/client-go/plugin/pkg/client/auth"

regards
Mathias

**Comment by chanwit** [comment]
Thank you so much @imathu for reporting and also for the way to fix the issue!
We'll create a PR shortly to include the fix.
