### ISSUE TITLE
tf-runner fails: "terraform-runner.tls-*" not found

### ISSUE THREAD

**Issue by faganihajizada** [weaveworks/tf-controller#372]
Hi 👋🏻 

We are having issues with the `tf-controller`. Sometimes the `tf-runner` pods fail and we see an error message like:

`2022/09/28 11:36:38 secrets "terraform-runner.tls-1664811349" not found`

This happens in case there was a namespace with the same name before and deleted. If we had a namespace X and deleted it, the next time when we create a new namespace with the name X, the `tf-runner` in the new namespace fails.

A workaround is to restart the `tf-controller` deployment. 

Any help is highly appreciated. Thanks!

**Comment by faganihajizada** [comment]
https://github.com/weaveworks/tf-controller/blob/main/api/v1alpha1/terraform_types.go#L35-L44

**Comment by chanwit** [comment]
Thank you for reporting this @faganihajizada !

**Comment by faganihajizada** [comment]
You are welcome @chanwit. Thanks for a great job!

We are assuming the `tf-controller `stores/caches information about namespaces somewhere. Could you please provide some details? Maybe we can contribute to fixing it.

**Comment by faganihajizada** [comment]
Seems like it is being stored in memory: https://github.com/weaveworks/tf-controller/blob/279ac91ba1a015c128bfea18d8417e423bb9abea/mtls/rotator.go#L287

**Comment by chanwit** [comment]
Yes, it is.
We need a mechanism to write it down again to a newly created namespace.
To do so, we need a K8s Informer to watch the namespace (re-)creation.

**Comment by faganihajizada** [comment]
Actually decreasing the value of [CAValidityDuration](https://github.com/weaveworks/tf-controller/blob/279ac91ba1a015c128bfea18d8417e423bb9abea/charts/tf-controller/values.yaml#L90) might help right? For example we make it to [refreshCertsInMemory](https://github.com/weaveworks/tf-controller/blob/279ac91ba1a015c128bfea18d8417e423bb9abea/mtls/rotator.go#L291) in each and every 5 minutes.

**Comment by chanwit** [comment]
Yes, you could try that. 

If the CA duration value is 5m and the lookahead time is 2m, the CA will be refreshed for like every 5-2 = 3 minutes.

The flag to trigger re-generation is here: https://github.com/weaveworks/tf-controller/blob/279ac91ba1a015c128bfea18d8417e423bb9abea/mtls/rotator.go#L261

**Comment by artem-nefedov** [comment]
Still hope to see this addressed.

**Comment by rattboi** [comment]
Also looking forward to this being fixed. we are having tf-runners run within ephemeral namespaces, and the controller gets confused if the namespace is removed/recreated, as described here.

**Comment by artem-nefedov** [comment]
Alternatively, an ability to disable certificate management in the controller in favor of using 3rd party tool (cert-manager or just service mesh with mTLS) would be an option too.

**Comment by LappleApple** [comment]
Closing as work over the past few months should have addressed this issue and we expect it to only occur in edge-case situations. Feel free to report a new bug should you encounter one.

**Comment by artem-nefedov** [comment]
Is there an ETA when the next stable release with this fix is expected?

**Comment by wangyi198682** [comment]
Is there any approach to re-generate the tls secret manually?

**Comment by chanwit** [comment]
Sorry we don't have it yet.

It's automatically controlled by the mTLS generator inside the controller now.

May I ask how would suggest to generate these TLS secrets?

Maybe via a new tfctl command?

**Comment by KevinGimbel** [comment]
Hello, I just hit this issue - or something very similar, the log was the same anyways. :) 

```
secrets "terraform-runner.tls-1786313979" not found 
```

Restarting `tf-controller` fixed it.

**Comment by artem-nefedov** [comment]
@KevinGimbel did you delete and re-create runner namespace at any point before this happened?

**Comment by KevinGimbel** [comment]
I do not think so, but I cannot say for sure.
