### ISSUE TITLE
Ability to specify imagePullSecret for runner pod image

### ISSUE THREAD

**Issue by tomhuang12** [weaveworks/tf-controller#373]

**Comment by Nalum** [comment]
This can be done with the service account but currently both service accounts use the same `imagePullSecrets` value. Might be good to have another one for the runner but fall back to the current setup?

Or do you mean to have this be part of the `Terraform` resource?

**Comment by tomhuang12** [comment]
Yeah, I built my runner with az cli and pushed it to a private registry. Maybe we can also change move runner pod image reference to `Terraform` instead of a env var of the controller?

**Comment by chanwit** [comment]
I though I already had a PR for this one. But it's probably on my local branch. Let me check.

**Comment by chanwit** [comment]
I though I already had a PR for this one. But it's probably on my local branch. Let me check.

**Comment by tomhuang12** [comment]
@Nalum Using service account `imagePullSecrets` worked for me for now :)
