### ISSUE TITLE
`make` does not work: `./tools/bin/protoc: No such file or directory`

### ISSUE THREAD

**Issue by Dentrax** [weaveworks/tf-controller#375]
```
$ git clone git@github.com:weaveworks/tf-controller.git
$ cdd tf-controller
$ make

./tools/bin/protoc --go_out=. --go_opt=Mrunner/runner.proto=runner/ --go-grpc_out=. --go-grpc_opt=Mrunner/runner.proto=runner/ runner/runner.proto
bash: line 1: ./tools/bin/protoc: No such file or directory
make: *** [gen-grpc] Error 127
```

Version: 279ac91ba1a015c128bfea18d8417e423bb9abea

**Comment by Dentrax** [comment]
Fixed the `protoc` path now it throws:

```
...
go: added sigs.k8s.io/structured-merge-diff/v4 v4.1.2
go: added sigs.k8s.io/yaml v1.2.0
/Users/furkan.turkal/go/src/tf-controller/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
bash: line 1: /Users/furkan.turkal/go/src/tf-controller/bin/controller-gen: No such file or directory
make: *** [generate] Error 127
```

**Comment by chanwit** [comment]
Please refer to the development guide. We use a very specific set of tools there.
Feedback to the guide is also appreciated.

https://github.com/weaveworks/tf-controller/blob/main/DEVELOPMENT.md

**Comment by Dentrax** [comment]
> We use a very specific set of tools there.

It's about installation _path_, not versions.

I already installed prerequisite tools as listed [here](https://github.com/weaveworks/tf-controller/blob/main/DEVELOPMENT.md#protobuf-setup). But this document does not indicate `protoc` binary must be in `./tools/bin/protoc`. We can add this.

I'd expect the `make` should "just" work without any additional configuration to increase the overall UX.
