### ISSUE TITLE
EPIC tf cli commands (create, delete, resume, suspend)

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#379]
I want to have a set of CLI commands that I can use to create, delete, resume, and suspend Terraform resources.

  - [ ] #380
  - [ ] #381
  - [ ] #382
  - [ ] #383

**Comment by JamWils** [comment]
@chanwit can we create these in the Weave GitOps CLI instead?  I would like to move away from the `tfcli` and absorb those commands into Weave GitOps.

**Comment by chanwit** [comment]
Yes that's what I planned.

tf is just a dummy name here.

**Comment by JamWils** [comment]
:), thanks

**Comment by chanwit** [comment]
moved this ticket to https://github.com/weaveworks/weave-gitops/issues/2968
