### ISSUE TITLE
support terraform debug logging

### ISSUE THREAD

**Issue by k0da** [weaveworks/tf-controller#393]
Currently there is no way to set TF_LOG and logging done on terraform-exec level

**Comment by k0da** [comment]
Yes, I did.

https://github.com/hashicorp/terraform-exec/blob/c3eeeea58419c22fda4600718d2a5245884af5ad/tfexec/terraform.go#L38

This is denied by terraform-exec go package

**Comment by chanwit** [comment]
I see. Then we cannot support that too.


But we have another flag for you to try.

https://github.com/weaveworks/tf-controller/blob/main/runner/server.go#L202

Hope it's useful a bit.

**Comment by Nalum** [comment]
We could look at exposing the `Terraform.SetLog` ([here](https://github.com/hashicorp/terraform-exec/blob/c3eeeea58419c22fda4600718d2a5245884af5ad/tfexec/terraform.go#L144))and related functions in some way.

**Comment by daveoy** [comment]
i came here to post this issue -- HELM_DEUBG="1" doesn't seem possible either. not that its rejected, its just ineffective.

would love to be able to do this.

**Comment by daveoy** [comment]
> We could look at exposing the `Terraform.SetLog` ([here](https://github.com/hashicorp/terraform-exec/blob/c3eeeea58419c22fda4600718d2a5245884af5ad/tfexec/terraform.go#L144)) and related functions in some way.

i can understand a TF_VAR_xxx env variable being prohibited but i would have though TF_LOG wouldn't be? especially when combined with the sensitive logs env var mentioned earlier.

if you can point me at where to run those SetLog and SetLogPath commands i'm happy to build the project and test their usage.

this is a big blocker for me right now as im seeing helm_release resources in terraform just run for hours and hours under the tf-controller and not make anything in GKE.

**Comment by Nalum** [comment]
@daveoy it's not that we are blocking them, I understand it that the tf-exec package blocks them so that they can be set by that package exclusively. In order to support those functions we will need to update tf-controller/tf-runner to allow them to be set.

@chanwit would it be best to make these part of the Terraform CRD? Something like `spec.setLog` or maybe group them all in `spec.tfExec`?

**Comment by chanwit** [comment]
`spec.logging: info # debug` would be possible, but I could see some security concerns.

https://github.com/weaveworks/tf-controller/blob/main/runner/server.go#L202

**Comment by chanwit** [comment]
We shall add this as the "observabilities" item to the roadmap.
