### ISSUE TITLE
Questions on using tf-controller - how do you create the TF resources?

### ISSUE THREAD

**Issue by absolutemikex** [weaveworks/tf-controller#410]
Hello Folks - a few simple questions. I plan on using this tool to deploy into different clouds such as AWS, OCI, GCP etc, as there are already providers created for these clouds. 

There are examples on creating the source object for the source controller - but what is in those repositories? Is it normal `.tf` files? Are there Kubernetes Objects defined with the resources?

For instance if I wanted to create a little API around tf-controller - would I create the source controller object, then K8s will look in a GitRepo or S3 bucket for the code, would I need to create those .tf files or k8s resources?

From what I saw, the Terraform would be regular terraform in a repo - then Flux would pick it up and deploy it. Is this correct?

**Comment by chanwit** [comment]
> There are examples on creating the source object for the source controller - but what is in those repositories? Is it normal .tf files? 

Yes, they are normal .tf files.

> For instance if I wanted to create a little API around tf-controller - would I create the source controller object, then K8s will look in a GitRepo or S3 bucket for the code, would I need to create those .tf files or k8s resources?

For the normal use cases, you can just create .tf files, and store them in the GitRepo.

> From what I saw, the Terraform would be regular terraform in a repo - then Flux would pick it up and deploy it. Is this correct?

Yes. It is correct.

**Comment by absolutemikex** [comment]
Thank you again @chanwit
