### ISSUE TITLE
TF Controller shutdown with the runners

### ISSUE THREAD

**Issue by Nalum** [weaveworks/tf-controller#412]
We've seen an issue now where the `tf-controller` is unable to talk to the `tf-runner`, we believe this is due to the different versions of the controller and the runner. This happened where the `tf-controller` is running on `v0.12` and has one or more runner pods running, the controller is then terminated and replaced with an older version which then cannot talk to the `v0.12` runners.

Should we have the `tf-controller` run any runner jobs to completion before it terminates?

**Comment by chanwit** [comment]
Our current execution model does not allow that as it's fully synchronous.

To do so, we have to change the execution model to be asynchronous, which is doable but more difficult.

**Comment by Nalum** [comment]
Is it something worth exploring? I could see this happening with upgrades as well

**Comment by chanwit** [comment]
Yes, of course.

**Comment by Nalum** [comment]
@chanwit would it make sense to have the controller check the version of the running container for the runner pod when it tries to get it and then if the runner version is not what's expected we kill that pod and create a new one with the expected version?
