### ISSUE TITLE
Add support for symbolic links inside a terraform workspace

### ISSUE THREAD

**Issue by masterphenix** [weaveworks/tf-controller#414]
Hello,
I have a terraform workspace that looks like this:
|- mycluster01
|--- myapp01
|----- main.tf
|----- common.tf
|--- myapp02
|----- main.tf
|----- common.tf

This works fine when I declare a Terraform object with this path (which is relative to the root of the gitRepository declared beforehand): 
`  path: ./mycluster01/myapp01`

Now, the common.tf file is the same for both project, so I would like to move it under "mycluster01", and then create symlinks inside folders myapp01 and myapp02: `common.tf -> ../common.tf`
When I do that, terraform behaves well and creates the plan accordingly on my local machine.
However, it seems that the runner doesn't like symlinks:
```
Error: Insufficient features blocks

  on <empty> line 0:
  (source code not available)

At least 1 "features" blocks are required.
{"level":"error","ts":"2022-10-13T10:47:05.830Z","logger":"runner.terraform","msg":"error creating the plan","error":"exit status 1\n\nError: Insufficient features blocks\n\n  on <empty> line 0:\n  (source code not available)\n\nAt least 1 \"features\" blocks are required.\n"}
```
This is because my provider is declared inside the common.tf file.

Would it be possible to add support for symbolic links ?

**Comment by eatwithforks** [comment]
Running into the same issue.

Repo structure:
|--- main.tf
|--- variables.tf
|--- modules/
      |--- variables.tf (symlink: ln -s ../variables .)
      |--- resource.tf 

The symlinked variables.tf isn't copied over in the tf-runner's /tmp/repo/

cc @chanwit Are there plans to support this?

**Comment by chanwit** [comment]
Hi @eatwithforks 
It seems to be out of control for us because TF-controller downloads files as a BLOB from the Source controller.

Maybe you could try the include capability of the Source controller to achieve the same result?
https://fluxcd.io/flux/components/source/gitrepositories/#include

**Comment by chanwit** [comment]
RE: symlinks

https://github.com/fluxcd/source-controller/blob/b939216694133ed4b9f332ac52ba0db2ef37d3a3/controllers/storage.go#L367-L375

The code is looking at each file or folder in a specific directory and checking if there is an error. If there is an error, it stops and returns that error. If there is no error, it checks if the current file is a regular file or a folder. If it is not a regular file or a folder (for example, symlinks), it will ignore that file and move on to the next one. It continues this process for every file and folder in the directory.

**Comment by chanwit** [comment]
I shall close this issue for now, but feel free to re-open it if you'd like a further discussion.
