### ISSUE TITLE
Question about State Configuration and Provider Secrets

### ISSUE THREAD

**Issue by absolutemikex** [weaveworks/tf-controller#415]
Hello,

Can you show me some example code of the Terraform Resource where a few things are specified - I've looked through the docs.

1. State file config - is this something I would configure in K8s? Or would it be how we normally do it in a `backend.tf` for example - also where do I reference the AWS secrets for instance when I want to s3 as the state?
2. Piggy backing on number 1, is there any example of setting up the secrets for different providers? For instance, for AWS would I create a secret with keys like AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and tf-controller is smart enough to understand that?

**Comment by chanwit** [comment]
Hi @absolutemikex 

1. This example might be useful for you: https://weaveworks.github.io/tf-controller/use_tf_controller/with_a_custom_backend/
2. Yes, they can be passed via environment variables like this:
```
spec:
  runnerPodTemplate:
    spec:
      envFrom:
      - secretRef:
          name: aws-credentials
```

**Comment by absolutemikex** [comment]
Thank you! That is exactly what I was looking for.
