### ISSUE TITLE
Docs TODO

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#418]
## Use
  - webhook (policy engine integration) // https://weaveworks.github.io/tf-controller/use_tf_controller/with_external_webhooks/#configuration-example
  - retryInterval // https://weaveworks.github.io/tf-controller/how_to/interval_and_retryInterval/
  - workspace https://weaveworks.github.io/tf-controller/adr/0003-workspace-blob-caching/
  - environment variable // https://weaveworks.github.io/tf-controller/use_tf_controller/with_tf_runner_logging/

## How to
  - write primitive modules // https://weaveworks.github.io/tf-controller/use_tf_controller/with_primitive_modules/

**Comment by LappleApple** [comment]
Added links where we provided docs and will close now.
