### ISSUE TITLE
Feature: writeOutputsToSecret within different namespace

### ISSUE THREAD

**Issue by adamstrawson** [weaveworks/tf-controller#429]
We have a use-case where we want the Secret containing outputs available within another namespace. 

As an example;
```
writeOutputsToSecret:
  name: helloworld-outputs
  namespace: foobar
```

If `writeOutputsToSecret.namespace` isn't set, defaults to the current `terraform.Namespace` value.

Happy to open a PR if you feel there is value in this feature?

**Comment by chanwit** [comment]
Hi @adamstrawson 

This feature had been brought up many times.
We follow the multi-tenancy principle of Flux, which does not violate the namespace boundary for security reasons.

There are many workarounds like using a secret sharing operator to help you achieve the same result, but sorry we don't have any plan to implement features that read / write secrets in the different ns.

**Comment by adamstrawson** [comment]
Thanks for the explanation @chanwit
