### ISSUE TITLE
Publish Tofu-Jet

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#435]
Tofu-Jet is a generator that converts Terraform providers into TF-controller's primitive modules.
This ticket is to track the progress of opensourcing Tofu-Jet.

**Comment by chanwit** [comment]
cc @steve-fraser

**Comment by tomhuang12** [comment]
Looking to use it for Azure resource :)

**Comment by akselleirv** [comment]
Hello @chanwit! Do you have any timeline for when this will be open-sourced?

**Comment by chanwit** [comment]
Unfortunately @akselleirv 

We de-prioritized this feature and now are spending time to implement other features at the moment.

**Comment by chanwit** [comment]
The generated modules are available here: https://github.com/tf-controller/aws-primitive-modules
