### ISSUE TITLE
implement `aws_dynamodb_table` primitive module

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#450]
As a platform engineer,
I'd like to create `aws_dynamodb_table` resource via TF-controller.

**Comment by chanwit** [comment]
Hi @JamWils @josefaworks 

Is it possible for you to help refine this ticket, as this feature is required by @steve-fraser?

**Comment by steve-fraser** [comment]
This is for ww infrastructure for terraform backends.

This will also be used for internal WGE provisioning for create a s3 bucket for the tf-controller

**Comment by JamWils** [comment]
@chanwit why can't the tf-controller do this today?

**Comment by chanwit** [comment]
Here's the context.

Before v0.13, every TF-controller use need to prepare 1. YAML files and 2. Their own TF files.

In v0.13.0, we have introduced the preview version of AWS package, a ready-to-use OCI bundle. So that the platform operators can use the package out of the box without writing Terraform files themselves.
(This feature gives a Crossplane-like experience to users.)

Currently, the alpha version of the package contains only subsets of the AWS resources. We opt out `aws_dynamodb_table` because it uses a complex HCL.
Now as it's required by our infra team, we would take this opportunity to polish a UX of the TF-controller from this angle.

**Comment by squaremo** [comment]
Still relevant @chanwit?

**Comment by chanwit** [comment]
We can close it for now.
