### ISSUE TITLE
Support ARM architecture docker images

### ISSUE THREAD

**Issue by xUnholy** [weaveworks/tf-controller#453]
I'd like to propose that the TF Controller support providing ARM architecture images; Ideally this is in the form of multi-architecture docker images to avoid the need to add additional selectors depending on machine types this could operate within.

Currently it doesn't work on ARM

```log
exec /sbin/tini: exec format error
```

Current GHCR image manifest https://github.com/weaveworks/tf-controller/pkgs/container/tf-controller/49066231?tag=v0.13.1

**Comment by chanwit** [comment]
Hi @xUnholy 

Thank you for reporting this.

Yep, the ARM support is a known issue.
It's on our roadmap, and will be implemented later probably by the first half of 2023.

**Comment by xUnholy** [comment]
Thanks @chanwit that would be awesome if it could be implement at the earliest convenience.

**Comment by madAndroid** [comment]
Hi @xUnholy  - just following up on older issues, it appears that we do have an ARM image in place now for Linux, you can find details at: https://github.com/weaveworks/tf-controller/pkgs/container/tf-controller - under `OS/Arch`

Can you please test this image out, and let us know if this is working as expected? Thanks :)

**Comment by LappleApple** [comment]
Closing as the ask has been fulfilled.
