### ISSUE TITLE
Support collection objects when using outputs from another Terraform resource

### ISSUE THREAD

**Issue by rparmer** [weaveworks/tf-controller#465]
Using outputs from one Terraform resource as inputs to another Terraform resource works great when outputted reference is a string.  However it seems to be interpreting collections (lists, maps and objects) as strings too.  For example if my parent Terraform outputs a list of strings
```
output "testing" {
  value = ["one", "two"]
}
```

and the child Terraform requires a list of strings
```
variable "testing" {
  type = list(string)
}
```

the child Terraform will blow up with `Invalid value for input variable ... list of string required`. I can view the output and verify the secret is storing the value correctly, but the `generated.auto.tfvars.json` is converting the array to a string
```
{...,"testing":"[\"one\",\"two\"]"}
```

I've been able to get around this by using the terraform_remote_state data lookup.  But it would be nice if the controller could support these types of output references.

**Comment by chanwit** [comment]
Thank you for reporting this @rparmer !!
