### ISSUE TITLE
Add extraInitContainer for state initialization, etc.

### ISSUE THREAD

**Issue by nwmcsween** [weaveworks/tf-controller#466]
As per title this will allow importing state manually without much fuss.

**Comment by chanwit** [comment]
I guessed the init container feature had been implemented recently by @Nalum 
Luke, could you please confirm that we already have this capability please?

**Comment by Nalum** [comment]
Yep, this was part of the v0.13.0 release :+1+

**Comment by Nalum** [comment]
You can see an example in this test https://github.com/weaveworks/tf-controller/blob/main/controllers/tc000311_init_container_test.go#L102-L107
