### ISSUE TITLE
Official guidance needed for tf-controller HA setup

### ISSUE THREAD

**Issue by tariq1890** [weaveworks/tf-controller#479]
Hi, we are currently using tf-controller and we plan to go live with it soon. One of our concerns with tf-controller is the lack of an HA strategy. 

As per this [helm chart comment](https://github.com/weaveworks/tf-controller/blob/main/charts/tf-controller/values.yaml#L21), it is recommended to use only one replica of the tf-controller pod. We have chosen to follow that guidance, but this is not a viable solution long term as we'd need like to distribute the tf-controller pods across AZs at the very least. AZ outages are fairly common and with the current setup, we leave ourselves vulnerable to these events.

Can we understand why replicaCounts greater than 1 are discouraged?What are the pending action items to  make the multi-replica-setup work?

**Comment by chanwit** [comment]
Hi @tariq1890 

You could set the replicas of TF-controller to 3.
Just like other Flux controllers, with 3 replicas, only 1 would be elected as the main controller while the other 2 would be blocked and waited until there's a new election signal.

**Comment by tariq1890** [comment]
Thanks for your response @chanwit . That makes sense, but could you clarify why it's documented that more than 1 replica is undesirable?

**Comment by tariq1890** [comment]
The comment is here: https://github.com/weaveworks/tf-controller/blob/main/charts/tf-controller/values.yaml#L21
