### ISSUE TITLE
non-locking plans

### ISSUE THREAD

**Issue by emalihin** [weaveworks/tf-controller#482]
Hello,

There are scenarios where we want to run the same state plan from multiple k8s clusters, for example:
* All dev->prod clusters create/manage the same Sentry project with the same config
* Multi-cluster scenario where there are two or more prod clusters manage the same infra with the same config

However we sometimes run into state-lock errors, where timings of plans clash, and plan that started second cannot run due to the first plan locking the state.

What do you think about adding an option to set `-lock=false` on the plan stage?

**Comment by chanwit** [comment]
Hi @emalihin 
Thank you for bringing this up.

It would add a good use case to the controller. Let's think of a field to specify this.

**Comment by emalihin** [comment]
Hi @chanwit, what do you think of `lockPlan` variable, that's defaulted to `true`?

**Comment by chanwit** [comment]
Maybe we better reverse the logic like what we did for drift detection as we have 

`.spec.disableDriftDetection`

which is false by default.

Say we would implement

.spec.disableLock / .spec.disableLocking 

for this purpose.

Wdyt @emalihin ?

Would love to hear your feedback too @Nalum

**Comment by Nalum** [comment]
Agree we should use something like `.spec.disableLock`, I'm not totally sure on the use cases. What's the reasoning behind having multiple clusters manage the same infrastructure?

I would assume we do not want to disable locking when an apply is actually going to be run?

**Comment by emalihin** [comment]
>What's the reasoning behind having multiple clusters manage the same infrastructure?
In a world where all clusters are created from the a "blueprint" - they are all identical and have the same components deployed.

>as the flag must be passed during Terraform initialization.
Is it a case that's specific to this project? Usually one can do `terraform init; terraform plan -lock=false ..; terraform apply ..`

**Comment by Nalum** [comment]
Is the state lock issue a short lived issue or once it's hit is that clusters instance is locked out and needs manual intervention?

It seems to me that you would hit the same issue with locking applies. Is there another way around this?

**Comment by emalihin** [comment]
>Is the state lock issue a short lived
it is short lived, plans are eventually green (until they clash again)

>same issue with locking applies
good point, applies would clash in a situation where there's actually something to apply.

An alternative approach could be adding `-lock-timeout=Ns` option? 
`-lock-timeout=0s       Duration to retry a state lock.`

This way a second parallel plan will wait for N minutes for lock to be released before failing the job.

**Comment by Nalum** [comment]
This seems like a good approach to me. What do you think @chanwit ?

**Comment by chanwit** [comment]
SGTM

**Comment by emalihin** [comment]
let me know what you think @chanwit @Nalum  https://github.com/weaveworks/tf-controller/pull/489/files
