### ISSUE TITLE
Configure an EKS Kubernetes provider

### ISSUE THREAD

**Issue by Smana** [weaveworks/tf-controller#486]
Hi everyone,

I'm currently testing this controller which is awesome because I'm a big fan of Flux generally speaking.
I'm able to create simple resources and it's pretty straightforward.
However, for my demo I'd like to create an EKS cluster and then install Flux and configure a few things.
For that I need to configure the `kubernetes` provider. Without tf-controller I would have done that as follows

```hcl
provider "kubernetes" {
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args = [
      "eks",
      "get-token",
      "--cluster-name",
      var.cluster_name
    ]
  }
}
```

However I'm not sure that's even possible. The error I get is pretty clear but I want to know what is your recommendation please.

```console
Error: Post "https://1B7085B8CBDF07A3521F20EE16512FCC.gr7.eu-west-3.eks.amazonaws.com/api/v1/namespaces": getting credentials: exec: executable aws not found
```

Thank you,

**Comment by Smana** [comment]
I'm gonna try with my own runner image that includes the aws CLI and let you know.

**Comment by Smana** [comment]
Well I just noticed this [PR](https://github.com/weaveworks/tf-controller/pull/446). Testing that

**Comment by chanwit** [comment]
Sorry for the late reply, @Smana 

For security reasons, we didn't want to ship AWS cli with our images. I'm guessing that we still have a way to retrieve Kubeconfig out of the cluster, without using the CLI. If there's no any other way to do so, we're happy to discuss the inclusion of AWS cli.

cc @Nalum and @tomhuang12 for further discussion.

**Comment by Smana** [comment]
@chanwit thanks for the answer, I understand the security context. I'm digging deeper to find out the best solution.

**Comment by Smana** [comment]
For those who are wondering if that adding the `aws` CLI actually works: I confirm
I was able to apply the code from my repository [here](https://github.com/Smana/flux-karpenter/tree/main/terraform/dev) (still work in progress).

```console
kubectl get tf -n flux-system 
NAME            READY   STATUS                                                           AGE
dev-karpenter   True    Plan no changes: main/28aadf68d7f1264b77888e65b39b785f686691c1   23m
```

**Comment by k0da** [comment]
@chanwit can you elaborate on security reasons?

**Comment by chanwit** [comment]
I want to minimize the attack surfaces of image. That's the main reason.
We need a guard rail to ensure that we really execute the intended AWS cli and not something else having the same name.

Let's discuss this measurement.

**Comment by k0da** [comment]
@chanwit this is configured on a provider level, the command and its arguments. It is up to user what to execute. And provider to validate it.

**Comment by chanwit** [comment]
Nop I mean the guard rail around authenticity of the `aws` cli itself before we execute it.
We need a kind of lock down + flag to allow us to reason that we're running something that may contain unverified / unsupported binaries.

**Comment by kaladaOpuiyo** [comment]
I did this to get it to work without the aws cli. 

```
data "aws_eks_cluster_auth"  "cluster" {
    name = "cluster"
 }

provider "kubernetes" {
  host                              = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
  token                            = data.aws_eks_cluster_auth.cluster.token
}
```

**Comment by k0da** [comment]
> ```terraform
> aws_eks_cluster_auth
> ```

It just this token is short lived (15minutes) and not refreshed. While exec plugin ensures it is up to date.

**Comment by chanwit** [comment]
@kaladaOpuiyo interesting
thank you so much.

I would try to set `.spec.force=true` in the auto apply mode to see if a Terraform object would generate a cluster token automatically at a certain interval.

**Comment by squaremo** [comment]
Can this be closed at this point? It seems like the immediate issue was resolved and there's a provisional way forward at least ("I did get it to work").

**Comment by LappleApple** [comment]
Closing -- we can reopen if necessary.
