### ISSUE TITLE
Question: Does tf-controller support JSON configuration syntax?

### ISSUE THREAD

**Issue by corkupine** [weaveworks/tf-controller#488]
We are using CDKTF, which synthesizes HCL as JSON. I think we *may* be able to leverage tf-controller if we commit the synthesized output, as long as tf-controller supports JSON.

Thanks for your help!

**Comment by chanwit** [comment]
Yes, I did a test and it worked just fine with CDKTF's JSON.
An extra step you would need to do is to remove the `backend` block from the generated JSON file.

**Comment by corkupine** [comment]
Thanks much, @chanwit!
