### ISSUE TITLE
Unable to create a runner with embeded provider binaries.

### ISSUE THREAD

**Issue by NM4** [weaveworks/tf-controller#507]
Hello,

I ty to create a new tf-runner image with embeded providers for air-gap use case without success !

I use the following Dockerfile to create the docker image on a connected workstation :

> 

_FROM ghcr.io/weaveworks/tf-runner:v0.13.1
USER root:root
WORKDIR /home/runner
COPY providers/ providers/
RUN cd providers/ && terraform init
RUN mkdir -p /home/runner/.terraform.d/plugins/ && cp -r providers/.terraform/providers/registry.terraform.io /home/runner/.terraform.d/plugins
RUN  chown -R 65532:65532 /home/runner/
USER 65532:65532_

> 

I configured The Terraform CRD to use the appropriate image that works correctly but the runner still try to download terraform providers from the internet.

It seems like the terraform process bootstrapped with Terraform-Exec library  don't henerits the all environment of the runner user.

regards.

**Comment by chanwit** [comment]
Hi @NM4 

Thank you for reporting this.
At the moment, we mount `/home/runner/` to be an empty dir so everything will be remove at the container mounting time.

The best bet for you would be having a separate dir for your plugins and cache then point it to terraform binary using the environment variables (which I forget their names - sorry about that).

**Comment by artem-nefedov** [comment]
Check out #321
