### ISSUE TITLE
question: is there a way to trigger a Terraform object reconciliation with its source object via CLI? like flux reconcile kustomize

### ISSUE THREAD

**Issue by aristapimenta** [weaveworks/tf-controller#512]
my current workaround is to push an empty commit and run a `flux reconcile source` command on the source object of the `Terraform` object

**Comment by tomhuang12** [comment]
Yes, you can use [tfctl](https://docs.gitops.weave.works/docs/terraform/tfctl/) to trigger a reconcile: `tfctl reconcile <resource-name>`.
