### ISSUE TITLE
Best way to autodiscover the VPC the controller is running in

### ISSUE THREAD

**Issue by danielloader** [weaveworks/tf-controller#513]
I've been creating clusters using eksctl and tf-controller is working well but I'm trying to work out the best way to give some sort of context to my terraform. I want to be able to deploy RDS and other resources in the VPC that was created by eksctl to launch the cluster thus forming a self contained deployment where in the bootstrap step is eksctl, then flux, which gets tf-controller and the rest just reconciles with helm charts to deploy the applications reliant on managed services.

Is there any existing patterns for the controller being aware of its locality in the AWS ecosystem; vpc-id, region, account-id?

**Comment by tomhuang12** [comment]
There isn't an existing pattern. I think to do this, you probably need an init container that [retrieves node metadata](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html) and storing them in a volume for the tf-runner container to use. Definitely an interesting use-case, let me know if you figure something out.

**Comment by LappleApple** [comment]
Closing as out of scope and addressed in part by previous comment.
