### ISSUE TITLE
`tfctl` is no longer managed as part of this repo, so it should be removed + docs should be updated

### ISSUE THREAD

**Issue by Gowiem** [weaveworks/tf-controller#516]
~It would be great to be able to install `tfctl` via `brew install tfctl`. I'm sure others would appreciate other package manager installation methods as well.~

`tfctl` is now merged in the `gitops` CLI tool, but there are references in the code (e.g. https://github.com/weaveworks/tf-controller/tree/main/tfctl) and documentation (e.g. https://docs.gitops.weave.works/docs/terraform/tfctl/#installation) that mention otherwise. Those should be cleaned up to decrease confusion for new folks trying out the project.

**Comment by Nalum** [comment]
`tfctl` has been merged into the Weave GitOps CLI,  see weaveworks/weave-gitops#3190 and https://docs.gitops.weave.works/docs/installation/weave-gitops/

**Comment by Gowiem** [comment]
@Nalum ah I didn't realize, thanks for pointing that out! There are docs that point to installing it through releases here: https://docs.gitops.weave.works/docs/terraform/tfctl/#installation

I'll update this ticket to be about updating docs.

**Comment by Nalum** [comment]
Ah good catch! I'll try tackling this as soon as I get time.

**Comment by artem-nefedov** [comment]
What is the weave gitops cli analog for `tfctl reconcile` command?

**Comment by chanwit** [comment]
No it's not 100% yet. We'll need to do more on this part. For the time being, please still feel free to continue with `tfctl`.

**Comment by squaremo** [comment]
`tfctl` stayed as its own thing, in the end.
