### ISSUE TITLE
Allow tf-controller Log Encoding to Be Configurable

### ISSUE THREAD

**Issue by shin-go** [weaveworks/tf-controller#522]
I have `v0.13.1` deployed for tf-controller with the `0.10.1` chart version. My organization uses `aws-for-fluent-bit` (since we use EKS) to ship event logs from clusters to Splunk Enterprise.

The logging format for tf-controller is hardcoded in the `deployment.yaml` template file, but it's commonly supported in the other gotk controller stack to be able to configure the `--log-encoding` arg to `console` aside from the default `json` value.

In my specific case, to get tf-controller's event logs "prettified" I would have to do some transformation on the Splunk Enterprise side of things. Without this prettification preprocessing before indexing in Splunk, you end up with JSON shoe horned into a String data type (in Splunk), which makes interpreting those events painful. It would be ideal to have the ability to specify the `--log-encoding` value as  `console` via a values.yaml override and substitution.

**Comment by chanwit** [comment]
Thank you for using tf-controller @shin-go !

Probably the best place to change it is in the Helm chart? @tomhuang12 what do you think?

**Comment by tomhuang12** [comment]
Yeah should be an easy change. I'll add something tomorrow.
