### ISSUE TITLE
Resource requests for runner pods

### ISSUE THREAD

**Issue by artem-nefedov** [weaveworks/tf-controller#526]
Is there a way to configure resource requests/limits for runner Pod? Looking at CRD spec (runnerPodTemplate section), I only found resources section for initContainers, and couldn't figure out how to set it for the main container. If there's currently no way, consider this a feature request.

**Comment by odise** [comment]
@chanwit is there any workaround for that problem? It's a bit problematic to guaranty CPU and RAM for the runners which leads into frozen pods in some cases. I was thinking about https://github.com/redhat-cop/patch-operator as last resort ...

**Comment by chanwit** [comment]
Will prioritize this feature to make sure it's included in v0.15.0. 

Thank you for the ping @odise.

**Comment by artem-nefedov** [comment]
@odise As a workaround, we do use [limit ranges](https://kubernetes.io/docs/concepts/policy/limit-range/) that force resource requests upon all pods that don't have them in the namespace. You can also use any mutating admission controller (e.g. [kyverno](https://kyverno.io/policies/other/add-default-resources/add-default-resources/)). However, these are all just that - workarounds - and they introduce more moving parts. A native support would be much better.

**Comment by creatorKoo** [comment]
> Will prioritize this feature to make sure it's included in v0.15.0.
> 
> Thank you for the ping @odise.

Can I know when this issue will be resolved?

**Comment by chanwit** [comment]
ouch. sorry that this work slipped thru the cracks, @creatorKoo @odise 

I put this on the board.

**Comment by LappleApple** [comment]
Relates to https://github.com/weaveworks/tf-controller/issues/786.

**Comment by chanwit** [comment]
@luizbafilho have we implemented this?
