### ISSUE TITLE
notifications-for-third-party-controllers not working with fluxcd v0.39.0 tf-controller v0.13.1

### ISSUE THREAD

**Issue by zipizapclouds** [weaveworks/tf-controller#532]
Hi

While configuring tf-controller to send notifications to fluxcd, I've followed the current instructions in [enable-notifications-for-third-party-controllers](https://fluxcd.io/flux/cheatsheets/bootstrap/#enable-notifications-for-third-party-controllers) but continuously got an error and Terraform-CRD notifications did not worked.

I've investigated and with these proposed changes to the patch, the notifications worked again, as intended.

It could be good to add these to the instructions in [enable-notifications-for-third-party-controllers](https://fluxcd.io/flux/cheatsheets/bootstrap/#enable-notifications-for-third-party-controllers) to help future users

I've crearted a MR on fluxcd/website: https://github.com/fluxcd/website/pull/1387

Creating this issue here on on tf-controller to reflect it elsewhere than in fluxcd/website, in the hope it might help others in this community facing the same situation

I've used recent versions of fluxcd and tf-controller:

tf-controller v0.13.1
fluxcd v0.39.0

Keep up the great work - cheers

**Comment by chanwit** [comment]
@zipizapclouds shall we close this?

**Comment by zipizapclouds** [comment]
Sure - thanks
