### ISSUE TITLE
Allowing tf-controller to apply to terraform manifest targeting resources

### ISSUE THREAD

**Issue by mcortinas** [weaveworks/tf-controller#537]
Hello,

 I'm moving some CD pipelines to tf-controller and I miss the option to allow me applying Terraform manifests targeting resources.
 
[Let me share HashiCorp documentation about targeting resources](https://developer.hashicorp.com/terraform/tutorials/state/resource-targeting)

[I think it could be interesting adding this feature as a field in TerraformSpec documented in this link](https://weaveworks.github.io/tf-controller/References/terraform/#infra.contrib.fluxcd.io/v1alpha1.TerraformSpec)

Best regards,
Marc

**Comment by chanwit** [comment]
Hi @mcortinas 

I think we have `.spec.targets` to support this feature:
https://github.com/weaveworks/tf-controller/pull/311
