### ISSUE TITLE
Error: must be no more than 63 characters - limit on labels.

### ISSUE THREAD

**Issue by vSivarajah** [weaveworks/tf-controller#547]
Hi! we are using tf-controller to provision kafka resources such as topics and schemas in Confluent Cloud, and it works wonderful. 

However, we have encountered an issue where the runner-pod is extracting the name of the pod to add the label. There is a 255 character limit on the name of the pod but only a 63 character limit on the label.

```
error":"Pod \"rolebinding-s99999-test-s99999-private-insight-usage-app-fct-tf-runner\" is invalid: metadata.labels
Invalid value: \"rolebinding-s99999-test-s99999-private-insight-usage-app-fct-tf-runner\": must be no more than 63 characters"}
```

In order for us to enforce uniqueness in topic-names and terraform CR's we need to have quite long names. 

Is there any possibility to change from using label to annotations for this specific label: https://github.com/weaveworks/tf-controller/blob/main/controllers/tf_controller_runner.go#L50

**Comment by vSivarajah** [comment]
Thanks for the quick reply @chanwit! sounds good!

**Comment by chanwit** [comment]
Changed severity to low for now as there's a workaround provided by @vSivarajah
