### ISSUE TITLE
How can I consume module privates from tf controller flux?

### ISSUE THREAD

**Issue by jjpecete** [weaveworks/tf-controller#552]
Hi guys, 

I think I have tried everything to make this run but I couldnt. I have tried to configure .terraformrc as secret, as volume, modifying the runner itself but nothing worked. Any ideas or any specific feature or configuration to get private modules from gitlab?

Thanks a lot

**Comment by chanwit** [comment]
Hi @jjpecete 
Could you please paste some snippets of your Terraform codes?

**Comment by overdrive3000** [comment]
Hi @jjpecete 

Have you tried setting an environment variable like the following one within the tf-runner pod?

```
TF_TOKEN_gitlab_com=${GITLAB_TOKEN}
```

Where `_gitlab_com` is the hostname of your private gitlab host, and GITLAB_TOKEN can be a personal access token with `read_api` permissions. That worked for me.

I created a secret with the environment variable and token then used the following to get the environment in the tf-runner pod:

```
  runnerPodTemplate:
    spec:
      envFrom:
      - secretRef:
          name: gitlab-token
```

Hope this help.

**Comment by LappleApple** [comment]
Closing due to lack of response but feel free to reopen if necessary. Will bookmark the solution above as a potential troubleshooting tip upon testing.
