### ISSUE TITLE
tfplan Secret data is compressed twice

### ISSUE THREAD

**Issue by hulquest** [weaveworks/tf-controller#555]
### Discussed in https://github.com/weaveworks/tf-controller/discussions/554

The tfplan data in the Secret can be viewed when it is decompressed twice.  

<div type='discussions-op-text'>

<sup>Originally posted by **hulquest** March 24, 2023</sup>
I'm not sure if this is a bug or know-how problem on my side so I'll start with a question.

I can decode and unzip tfstate Secrets without issue.  However, using the same technique I can't decode tfplan Secrets into readable text.

`k get secrets tfstate-default-curly-voice-mcjc6s -o jsonpath={.data.tfstate} |base64 -d  |gzip -d` --> good
`k get secrets tfplan-default-curly-voice-mcjc6s -o jsonpath={.data.tfplan} |base64 -d  |gzip -d` --> data still looks compressed.  Heres a sample of the output of tfplan data:
```
                                        h8dAZkvق"p+nTGkB:7%>`>
                                                              ƈ$=wY^>vb
                                                                       ߉e|(;Qj[3<PNN)dק\9=qyK>Epuu|WּZP52
f
hTXl('?ayprۥ
            `-[$!i])ʹ#\z
                        FQFiQ1  (8LnWȅa0J0IF%8]rQQp7Α
1$      ]                                            =]p7LQۛqwk}"
  )p;NucgtOѰ%:W@1ǝn10`
                      A܎"`lB% 0N
l7B`=F  đ)qPCtIn01Fi
```
The code looks fine to me but I don't have a dev env setup to step through with the debugger.  

I wanted to ask the community if there is something I'm missing before logging an issue.</div>

**Comment by LappleApple** [comment]
Thanks for filing -- closing this issue in light of https://github.com/weaveworks/tf-controller/discussions/554#discussioncomment-6767079.
