### ISSUE TITLE
Force unlock doesn't work with delete path

### ISSUE THREAD

**Issue by mehtameha1** [weaveworks/tf-controller#560]
When the Terraform CR is being deleted with 'destroyResourcesOnDeletion' set to true, it will delete the backend resources. If the tf-controller pod gets restarted during the backend resources deletion, the Terraform resource may get into a lock error state. To resolve the lock error, we are attempting to force an unlock with the following code:

```
 tfstate:
   forceUnlock: "yes"
   lockIdentifier: 49829de4-6475-d73f-1785-489ecb1c8e1d
```

However, it appears that this method does not work when the Terraform resource is being deleted. Therefore, we request support for force unlock with the delete path.

**Comment by tomhuang12** [comment]
I think the problem is really tf-controller not handling restart/termination well as addressed [here](https://github.com/weaveworks/tf-controller/issues/531). It shouldn't get into that bad state in the first place.

**Comment by mehtameha1** [comment]
tf-controller should handle restart/termination well to avoid getting into locked state. But since ForceUnlock is supported by tf-controller, it should work for delete path as well.
