### ISSUE TITLE
Missing azure Ci

### ISSUE THREAD

**Issue by sunilvishvakarma** [weaveworks/tf-controller#562]
Hi Team, 

When I try to create an azure resource via  tf-controller I get the below error 

code :

```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "3.24.0"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "this" {
  name     = "flux-test"
  location = "East US"
  }
```

This is the simple block of code we are using to create the azure resource group,  but when I tried this getting the below error.

```
 Error: building AzureRM Client: please ensure you have installed Azure CLI version 2.0.79 or newer. Error parsing json result from the Azure CLI: launching Azure CLI: exec: "az": executable file not │
│  found in $PATH.
```

Could you please help me to resolve this issue? 

And having one more question, to install any azure resources we need to provide access details of the azure portal, how to pass it?

**Comment by chanwit** [comment]
Hi @sunilvishvakarma 
Thank you for trying tf-controller.

I think @tomhuang12 would be able to help this out?

**Comment by sunilvishvakarma** [comment]
@tomhuang12  - Could you please can you give your input in this? 

Even though I have tried the solution which is provided here #221 , I added the azure-cli package in the docker file and created my own image, but even in the custom image azure-cli is not working! I get the below error :(   


`/ $ az --version
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/site-packages/azure/cli/__main__.py", line 14, in <module>
    from azure.cli.core import telemetry
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/telemetry.py", line 19, in <module>
    from azure.cli.telemetry import DEFAULT_INSTRUMENTATION_KEY
  File "/usr/local/lib/python3.11/site-packages/azure/cli/telemetry/__init__.py", line 9, in <module>
    import portalocker
  File "/usr/local/lib/python3.11/site-packages/portalocker/__init__.py", line 5, in <module>
    from . import utils
  File "/usr/local/lib/python3.11/site-packages/portalocker/utils.py", line 366, in <module>
    class BoundedSemaphore(LockBase):
  File "/usr/local/lib/python3.11/site-packages/portalocker/utils.py", line 388, in BoundedSemaphore
    directory: str = tempfile.gettempdir(),
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/tempfile.py", line 299, in gettempdir
    return _os.fsdecode(_gettempdir())
                        ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/tempfile.py", line 292, in _gettempdir
    tempdir = _get_default_tempdir()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/tempfile.py", line 223, in _get_default_tempdir
    raise FileNotFoundError(_errno.ENOENT,
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/']`

**Comment by tomhuang12** [comment]
Have you tried the Azure runner image we created? `ghcr.io/weaveworks/tf-runner-azure:v0.14.0`

```
$ docker run  -it --entrypoint /bin/sh ghcr.io/weaveworks/tf-runner-azure:v0.14.0
/ $ az --version
azure-cli                         2.40.0 *

core                              2.40.0 *
telemetry                          1.0.8

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location '/usr/bin/python3'
Extensions directory '/home/runner/.azure/cliextensions'

Python (Linux) 3.10.10 (main, Feb  9 2023, 02:08:34) [GCC 11.2.1 20220219]

Legal docs and information: aka.ms/AzureCliLegal


You have 2 update(s) available. Consider updating your CLI installation with 'az upgrade'
```

**Comment by masashi-noguchi** [comment]
I also got the same error on azure. Using the tf-runner-azure image did not solve the error. In my case, I switched using msi method. (this method does not use az command.) 

sample code
```
  runnerPodTemplate:
    metadata:
      annotations:
        azure.workload.identity/inject-proxy-sidecar: "true"
    spec:
      env:
      - name: ARM_CLIENT_ID
        value: xxxxx
      - name: ARM_SUBSCRIPTION_ID
        value: xxxxx
      - name: ARM_TENANT_ID
        value: xxxxx
      - name: ARM_USE_MSI
        value: "true"
```
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/managed_service_identity#configuring-terraform-to-use-a-managed-identity
https://learn.microsoft.com/en-us/azure/aks/workload-identity-migrate-from-pod-identity?source=recommendations#deploy-the-workload-with-migration-sidecar

just for your information.

**Comment by sunilvishvakarma** [comment]
I have used  ghcr.io/weaveworks/tf-runner-azure:v0.14.0 as a base image and built by customer tf-controller images and deployed on the Azure cluster, now I am getting the below error ..!

OSError: [Errno 30] Read-only file system: '/home/runner/.azure'


it seem the user home directory is mounting as read-only, any thoughts on this? below is my customized deployment file.

[tf-controller.deployment.txt](https://github.com/weaveworks/tf-controller/files/11158803/tf-controller.deployment.txt)

**Comment by tomhuang12** [comment]
@sunilvishvakarma I am not sure about your custom image `algiaccrmuseasunil.azurecr.io/azure-cli-alpine:1.0.7`. 

Have you tried the chart and override https://github.com/weaveworks/tf-controller/blob/main/charts/tf-controller/values.yaml#L108 to `ghcr.io/weaveworks/tf-runner-azure:v0.14.0`?

**Comment by LappleApple** [comment]
Closing due to lack of response but feel free to reopen if necessary.
