### ISSUE TITLE
[Spike] Adding a Buffer for Sanitizing Outputs and Enabling Secure Logs

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#564]
## User Story

As a developer, I'd like to add a buffer for sanitizing outputs and enable secure logging so that sensitive data is protected and not exposed in logs, ensuring compliance with privacy regulations and maintaining user trust.

## Acceptance Criteria

 - The runner should be able to identify and classify sensitive data (e.g., personally identifiable information, confidential information, etc.) in outputs before logging.
 - The runner should implement a buffer for sanitizing sensitive data in outputs, replacing or masking the data with a placeholder (e.g., "REDACTED" or "********") before it is logged.

## Spike basis for getting started 

- We might need to wait for something to happen or take a look at each step of a TF lifecycle and then try to tackle the steps one by one.
- [Example](https://github.com/weaveworks/tf-controller/blob/fb6716d7071b8011c59caf86510c8af0dc74f607/runner/server_plan.go#L45) (very specific to one case)
- How can we mask something that might be available in any format (tokens, IDs, etc.)? How to create rejects or formats? Will be flawed by design? 
- Possible answer to previous point: input and output variables... most secrets are coming from input variables

**Comment by LappleApple** [comment]
Will be handled alongside https://github.com/weaveworks/tf-controller/issues/517

**Comment by LappleApple** [comment]
Need to break this down

**Comment by yitsushi** [comment]
As a starting point, we can get check values from https://github.com/weaveworks/tf-controller/blob/main/runner/server_generate_tf_vars.go#L212

**Comment by yitsushi** [comment]
I think we have nothing to do here:

> As I was playing around, I realised as a user I WANT to see secrets in the output (the output we save in a secret at the end of apply) because that's the only place a generated secret key/token is accessible, without being able to see it, i may not able to obtain it any other ways.
>
> The plan output  can be filtered in some ways but only the human readable, the non-human readable seems (not a little bit) complicated.
>
> The logs are already sanitised with a [sanitizeLog](https://github.com/weaveworks/tf-controller/blob/fb6716d7071b8011c59caf86510c8af0dc74f607/runner/server_plan.go#L45)
