### ISSUE TITLE
Integration of Open Policy Administration integration(OPA)

### ISSUE THREAD

**Issue by sunilvishvakarma** [weaveworks/tf-controller#565]
Hello, 

I Have a question, do we have options to use/integrate Open Policy Administration integration(OPA) in terraform controller?  since it will help us to write our own policies to control the terraform deployments?

**Comment by tomhuang12** [comment]
One option is to run OPA test on the CI process before it is merged. You can use OPA's [github action](https://github.com/open-policy-agent/setup-opa).

**Comment by chanwit** [comment]
Hi @sunilvishvakarma

We actually have a policy engine integration built-in for Terraform plans as well as Terraform CRs.
The policy engine is also based on the Rego language of OPA, which slightly object layouts (as we also support Terrform plan validations in one go).

Good news is that our policy engine will be open sourced. (Sorry that I cannot say anything about ETA yet). In the mean time, you can take a look at the object layout supported by our controller here:

https://github.com/weaveworks/tf-controller/blob/be987f0b3f1494de2703486603b2935a1d94b17d/controllers/tf_controller_webhooks.go#L40

More to come and I'll keep you posted.

**Comment by sunilvishvakarma** [comment]
@chawklit - Thank you for your comments, 

As I got to know from your comments, currently tf controller is using policy engine integration built-in for Terraform plans as well as Terraform CRs,  just wanted to know what kind of policies is supported.

We expected some policies like, 
- When the approve plan is set to auto when the terraform plan shows it deleting something it should wait for the approvals, or it should deploy auto
- plan approvals should be controlled, as seen in some demos, now the authentication can be controlled at the repo level

once its becomes open source, based on the use cases we can improve further more

**Comment by chawklit** [comment]
@chanwit - I believe @sunilvishvakarma meant to ask you the questions above but tagged me instead.  Meant to write back before but was out of town, my apologies.

@sunilvishvakarma - Lucky we both worth for Weaveworks.  :)

**Comment by chanwit** [comment]
@chawklit Thank you Jeff. We are just few characters away ;-)

@sunilvishvakarma Sure. I'll ping you when the policy engine is opensourced

**Comment by LappleApple** [comment]
Hi all: Just stumbled upon this issue. Here's the link to the policy agent: https://github.com/weaveworks/policy-agent
