### ISSUE TITLE
Error getting the OCI artifact in Terraform resource

### ISSUE THREAD

**Issue by mcortinas** [weaveworks/tf-controller#572]
Hi, 

 Today I have a new issue in my Terraform object. 
 Let me share the error event 
```
ArtifactFailed
failed to verify artifact: computed checksum 'd277e64c9db8a92f9c6cb4c25446defbe2bc62e5f5a23721c6d154eaaeaeb89f' doesn't match advertised ''
```
![image](https://user-images.githubusercontent.com/692263/233046596-56ff3559-b778-4b42-8792-87265e45f622.png)
Let me share the Terraform object
```
kind: Terraform
spec:
  sourceRef:
    kind: OCIRepository
    name: dynamic-staging00.edreams.com
...
status:
  conditions:
    - lastTransitionTime: '2023-04-19T10:16:31Z'
      message: >-
        failed to verify artifact: computed checksum
        'd277e64c9db8a92f9c6cb4c25446defbe2bc62e5f5a23721c6d154eaaeaeb89f'
        doesn't match advertised ''
      reason: ArtifactFailed
      status: 'False'
      type: Ready
  lastAttemptedRevision: >-


    gitops2gitops@sha256:267973ca1e69579d337075c2b2cc8a2b07ce896e0b1971a4248c127a4c0cb54a
  observedGeneration: 1
```
Let me attach also the OCIRepository yaml resource in this file [OCI.tar.gz](https://github.com/weaveworks/tf-controller/files/11271986/OCI.tar.gz)

This error appeared after move from Upgrade from flux 0.40.0 to v2.0.0-rc.1 and tf-controller from v0.14.0 to v0.15.0-rc.1.
I removed all Terraform objects , removed FLUX and tf-controller CRDs and installed the new ones with the updated version and this error start appearing.

Let me describe my environment
```
k8s / GKE in v1.23.16-gke.1400
Flux v2.0.0-rc.1
tf-controller' with v0.15.0-rc.1 chart with version '0.12.0'
Source-controller: [ghcr.io/fluxcd/source-controller:v1.0.0-rc.1](https://ghcr.io/fluxcd/source-controller:v1.0.0-rc.1)
Argo CD v2.6.6+6d4de2e
NOT Flamingo implementation, everything installed from Terraform providers.....
```

**Comment by chanwit** [comment]
exactly, you need v0.15.0-rc.1 for Terraform controller as well as a new version (not released yet) Flamingo to do so (in case that you use Flamingo).

otherwise, you would need to be with v0.40.x or v0.41.x to avoid this error.

**Comment by mcortinas** [comment]
Wow @chanwit very fast answering! Thank you very much!
I think I'm going to downgrade flux to 0.41.x without flamingo by now.

**Comment by aristapimenta** [comment]
I don't use Flamingo or ArgoCD, just Flux and tf-controller and I'm on the same versions: `Flux v2.0.0-rc.1` and `tf-controller with v0.15.0-rc.1`. how should I fix the issue?

**Comment by aristapimenta** [comment]
oh, sorry, actually I was using `v0.14.0` because of this in the `HelmRelease` `.spec.values`:

```
    image:
      tag: v0.14.0
    runner:
      image:
        tag: v0.14.0
```

then I changed both to `v0.15.0-rc.1` and the problem was fixed

**Comment by chanwit** [comment]
Hi @aristapimenta 

Glad to see you've got it solved.

**Comment by chanwit** [comment]
I shall close the issue for now.
Please feel free to reopen, if the problem still persists.
