### ISSUE TITLE
Explore options for designing and creating a mini controller to communicate with the K8s API server

### ISSUE THREAD

**Issue by yitsushi** [weaveworks/tf-controller#581]
The Mini Controller is a logical subsystem within the BBP (Branch-based Planner) executable. It is designed to interact with the Webhook Receiver (another logical system in the same program) and handle incoming Pull Request (PR) information.

### Mini Controller Functionality

The Mini Controller is responsible for the following tasks:
  - Receive PR information from the Webhook Receiver.
  - Locate and manipulate various objects based on the received PR information.
  - Post a readable plan back to the PR.

### Implementation Steps

To implement the Mini Controller, we may follow these steps:

1. Set up Go-routines
  - Ensure that the Webhook Receiver and Mini Controller live in their own Go-routines within the BBP program.

2. Receive PR information
Upon receiving PR information from the Webhook Receiver, perform the following steps:
  - Locate the GitRepository object using the Git repo information from the PR. Refer to this object as `g1`.
  - Locate the Terraform object using the path information from the PR. Refer to this object as `t1`.
  - Locate the secret that stores the tfstate of `t1`. Refer to this Secret as `s1`.
  - Pause `t1` (e.g. via controller-runtime annotation)

3. Clone objects and configure
  - Clone objects `g1` and `t1` into new objects, say `g2` and `t2`. Link them together, so `t2.sourceRef` == `g2`.
  - Duplicate `s1` as `s2`. So `t2` would plan against tfstate information in `s2`.
  - Configure `t2` by setting `spec.approvalPlan` to an empty string and `spec.storeReadablePlan` to `human`. This will allow it to create a readable plan in a ConfigMap, say `cm1`, after each planning step.

4. Post plan back to PR
  - Read the plan from the content of `cm1` and post it back to the PR.

**Comment by yitsushi** [comment]
@chanwit : What exactly will the mini controller do?

**Comment by chanwit** [comment]
I'll refine its tech details and get back to you.

**Comment by chanwit** [comment]
ping @yitsushi I added tech details as a guideline to implement the mini controller. Please feel free to discuss.

**Comment by chanwit** [comment]
I think I found something that does not match with the current workflow of the tf-controller.
I'll do another revision to improve it and get back to you.
