### ISSUE TITLE
Assess methods to establish a secure connection between the hook receiver and the mini controller

### ISSUE THREAD

**Issue by yitsushi** [weaveworks/tf-controller#582]

**Comment by yitsushi** [comment]
@chanwit : Is there any communication between the mini-conrtoller and a webhook receiver, or the webhook receiver will create a custom resource "branch based planner", and the mini-controller will pick that up on reconcile?

If the former, then we need an grpc server on the mini-controller (or any kind of listener) and that's the scope of this issue to figure out what can we use and how.

If the latter, I don't think we have anything to do with this other than "manage CR from the webhook receiver" (delete on "merge/close", create on "open").

**Comment by chanwit** [comment]
It would be the latter.

Webhook receiver and a mini controller that talks to K8s API would be two logical sub-systems inside the executable you've created in #579

**Comment by yitsushi** [comment]
Created #586 as an action item from this. I don't think we need anything else than state management. I see only 3 actions now: create, delete, and annotate (to force re-run).

It is possible we find more actions with #583.
