### ISSUE TITLE
Analyze various GitHub event types and determine how to handle them in the planner system

### ISSUE THREAD

**Issue by yitsushi** [weaveworks/tf-controller#583]
We have two kind of events:
1. PullRequest sync
2. Issue comment

**PullRequest Sync**

Follow the possible "action" values from the PullRequest [webhook][1] and [event][2] docs and write a plan about what actions we want to handle and how.

**Issue comment**

Follow the possible "action" values from the Issue comment [webhook][3] and [event][4] docs and write a plan about what actions we want to handle and how.

Note: Pull Requests are handled as Issues by GitHub, so we have to ignore a lot of extra noise coming from other comments (from issues). We need a way to scope down and drop unwanted events as soon as possible in the process chain.

[1]: https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=opened#pull_request
[2]: https://docs.github.com/en/webhooks-and-events/events/github-event-types#pullrequestevent
[3]: https://docs.github.com/webhooks-and-events/webhooks/webhook-events-and-payloads#issue_comment
[4]: https://docs.github.com/en/webhooks-and-events/events/github-event-types#issuecommentevent

**Comment by yitsushi** [comment]
## Pull Request

### Payload

```json
{
  "action": "ACTION",
  "number": 3,
  "pull_request": {
    "number": 3,
    "state": "open",
    "title": "Title of the PR",
    "labels": [
      { "name": "something" }
    ],
    "head": {
      "ref": "new-branch",
      "sha": "0000000000000000000000000000000000000000",
      "repo": {
        "name": "repo-name",
        "full_name": "org/repo-name"
      }
    }
    "merged": false,
    "draft": false
  }
}
```

### Events

Actions to handle:

* `opened`: Create a custom resource.
* `reopened`: Create custom resource.
* `closed`: Delete custom resource.

Can we skip this event? If the branch was updated the custom resource stays the
same and the controller will reconcile it on next cycle? Or do we want to force
(annotate I guess) reconcile and let it ignore the `interval` on the CR?
* `synchronize`: Update custom resource / reconcile again.

All other actions can be ignored.

**Comment by yitsushi** [comment]
## Issue Comment

### Payload

```json
{
  "action": "created",
  "issue": {
    "number": 3,
    "state": "open",
    "title": "Title of the PR",
    "labels": [
      { "name": "something" }
    ],
    "pull_request": {}
  },
  "comment": {
    "body": "comment message",
    "author_association": "COLLABORATOR"
  }
}
```

If the `pull_request` key is there, it's a Pull Request, otherwise we can ignore
the whole event.

> Note: GitHub's REST API considers every pull request an issue, but not every
> issue is a pull request. For this reason, "Issues" endpoints may return both
> issues and pull requests in the response. You can identify pull requests by
> the pull_request key. Be aware that the id of a pull request returned from
> "Issues" endpoints will be an issue id. To find out the pull request id, use
> the "List pull requests" endpoint.
>
> Source: [docs.github.com][github-pr-as-issue]

Additional queries may be required to get the Pull Request information from the Issue information.

[github-pr-as-issue]: https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#list-issues-assigned-to-the-authenticated-user

### Events

Events to handle:

* `created`: Parse message, if message contains a specified "command", act based
on the command.

Commands: (the prefix is just an example here)

* `!restart`: Force rerun the plan.
* `!replan`: Force rerun the plan.

**Comment by yitsushi** [comment]
@chanwit : Does this look reasonable starting point? Anything to add or remove?

**Comment by chanwit** [comment]
LGTM for now. Thank you @yitsushi 
I like the way you use ! for force.
