### ISSUE TITLE
GOTK Metrics

### ISSUE THREAD

**Issue by Nalum** [weaveworks/tf-controller#585]
I've been looking into metrics and alerting and found that the tf-controller doesn't fully align with the metrics that Flux provide, I think it would be worth bringing the tf-controller and tf-runner inline and maybe make use of the Flux metrics package https://github.com/fluxcd/pkg/blob/main/runtime/metrics/recorder.go#L42-L68

I've seen that we have `gotk_reconcile_condition` and `gotk_suspend_status` and appear to be missing `gotk_reconcile_duration_seconds` and others which may not be relevant. 

========

**User Story**

As an SRE/DevOps Engineer, I need the `tf-controller` and `tf-runner` to provide the same metrics as those offered by the Flux metrics package to monitor and troubleshoot application performance and behavior effectively.

**Acceptance Criteria**

- [ ] The `tf-controller` and `tf-runner` should use the Flux metrics package. This can be checked by evaluating the implementation of these components for using Flux's `recorder.go`.

- [ ] The `tf-controller` and `tf-runner` should provide the `gotk_reconcile_duration_seconds` metric in line with Flux. This can be verified by generating this metric during a test run and checking if it is correctly recorded and visible in the monitoring dashboard.

- [ ] Compared to the Flux metrics package, all other relevant metrics currently missing should be included in the `tf-controller` and `tf-runner`. This can be validated by comparing the metrics provided by these two components with those offered by Flux and ensuring that relevant metrics are included.

**Comment by LappleApple** [comment]
@chanwit to add tasks and ACs
