### ISSUE TITLE
documentation: least required permissions for a github api token

### ISSUE THREAD

**Issue by yitsushi** [weaveworks/tf-controller#610]
Research and document what is the least required permissions set for a GitHub Token that can:
 - List PullRequest for a repository
 - Get PullRequest information
 - List Comments for a PullRequest (it will count as "issue comment")
 - Make a comment under a PR.

Type of tokens:
 - Fine-grained personal access tokens
 - Personal access tokens (classic)

Fine-grained token sounds good, but can we use and recommend it? It's still marked as "Beta".

Expected outcome:
There is a document that describes how to create a GitHub API Token, what permissions it needs to work with the branch-based planner, and what type of token is recommended.

**Comment by yiannistri** [comment]
We should also include how the token will be used for multiple repos https://github.com/weaveworks/tf-controller/pull/644#discussion_r1229255503
