### ISSUE TITLE
running NewTerraform: rpc error: code = Unknown desc = no kind "Terraform"

### ISSUE THREAD

**Issue by mcortinas** [weaveworks/tf-controller#614]
Hi,

 I've recently upgraded my environment and I started see this error trace in all my Terraform objects

```running NewTerraform: rpc error: code = Unknown desc = no kind "Terraform" is registered for version "infra.contrib.fluxcd.io/v1alpha2" in scheme "pkg/runtime/scheme.go:100"``` 

 Let me share the version of my environment:
`Kubernetes: v1.24.11-gke.1000
Flux: v2.0.0-rc.1
Weave GitOps: v0.23.0
image: ghcr.io/weaveworks/tf-controller:v0.15.0-rc.1
tf-controller chart helm in revision 	0.12.0
`

I also tried with Flux v2.0.0-rc.3 with same behaviour...

**Comment by chanwit** [comment]
Could you try the image from the main branch?

**Comment by mcortinas** [comment]
Hi,

 It seems it doesn't work fine, I only changed container image in tf-controller. Pod has started well and it's Running.  I also detected the old TLS secrets was removed but the Terrraform object doesn't work. Let me share some traces 

`{"level":"error","ts":"2023-05-21T15:11:42.105Z","msg":"Reconciliation failed after 15.10627237s, next try in 30s","controller":"terraform","controllerGroup":"infra.contrib.fluxcd.io","controllerKind":"Terraform","Terraform":{"name":"acc
ount-liligo","namespace":"fluxcd-cloudflare"},"namespace":"fluxcd-cloudflare","name":"account-liligo","reconcileID":"9fe17a63-7949-4775-9bb8-aa01ded85a86","reconciliation-loop-id":"33ce6706-907b-4d0c-9ddf-37e51b0831a2","start-time":"2023
-05-21T15:11:26.999Z","revision":"main@sha256:59a9a96fa0f21bd713646873d89e2560dd0adbe4999d3c84c14a21dae3c206fd","error":"error running NewTerraform: rpc error: code = Unknown desc = no kind \"Terraform\" is registered for version \"infra
.contrib.fluxcd.io/v1alpha2\" in scheme \"pkg/runtime/scheme.go:100\""}                                                                                                                                                                      
{"level":"info","ts":"2023-05-21T15:11:47.345Z","logger":"cert-rotation","msg":"gc: scanning old TLS artifacts","namespaces":["fluxcd-cloudflare","flux-system"]}                                                                            
{"level":"info","ts":"2023-05-21T15:11:47.345Z","logger":"cert-rotation","msg":"gc: found TLS artifacts","count":10}                                                                                                                         
{"level":"info","ts":"2023-05-21T15:11:47.352Z","logger":"cert-rotation","msg":"gc: successfully deleted old TLS Secret","namespace":"fluxcd-cloudflare","secret":"terraform-runner.tls-1684273966"}                                         
{"level":"info","ts":"2023-05-21T15:11:47.360Z","logger":"cert-rotation","msg":"gc: successfully deleted old TLS Secret","namespace":"fluxcd-cloudflare","secret":"terraform-runner.tls-1684311606"}                                         
{"level":"info","ts":"2023-05-21T15:11:47.368Z","logger":"cert-rotation","msg":"gc: successfully deleted old TLS Secret","namespace":"fluxcd-cloudflare","secret":"terraform-runner.tls-1684443115"}                                         
{"level":"info","ts":"2023-05-21T15:11:47.375Z","logger":"cert-rotation","msg":"gc: successfully deleted old TLS Secret","namespace":"fluxcd-cloudflare","secret":"terraform-runner.tls-1684485163"}                                         
{"level":"info","ts":"2023-05-21T15:11:47.384Z","logger":"cert-rotation","msg":"gc: successfully deleted old TLS Secret","namespace":"fluxcd-cloudflare","secret":"terraform-runner.tls-1683927461"}                                         
{"level":"info","ts":"2023-05-21T15:11:47.394Z","logger":"cert-rotation","msg":"gc: successfully deleted old TLS Secret","namespace":"fluxcd-cloudflare","secret":"terraform-runner.tls-1684274206"}                                         
{"level":"info","ts":"2023-05-21T15:11:47.401Z","logger":"cert-rotation","msg":"gc: successfully deleted old TLS Secret","namespace":"fluxcd-cloudflare","secret":"terraform-runner.tls-1684356064"}                                         
{"level":"info","ts":"2023-05-21T15:11:47.408Z","logger":"cert-rotation","msg":"gc: successfully deleted old TLS Secret","namespace":"fluxcd-cloudflare","secret":"terraform-runner.tls-1684556881"}                                         
{"level":"info","ts":"2023-05-21T15:11:47.417Z","logger":"cert-rotation","msg":"gc: successfully deleted old TLS Secret","namespace":"fluxcd-cloudflare","secret":"terraform-runner.tls-1684557943"}                                         
{"level":"info","ts":"2023-05-21T15:11:47.425Z","logger":"cert-rotation","msg":"gc: successfully deleted old TLS Secret","namespace":"fluxcd-cloudflare","secret":"terraform-runner.tls-1684644643"}                                         
{"level":"info","ts":"2023-05-21T15:11:47.425Z","logger":"cert-rotation","msg":"gc: finished deleting old TLS artifacts","count":10}   `

**Comment by chanwit** [comment]
That's strange.
Do you have this value?

```
$ kubectl get crd/terraforms.infra.contrib.fluxcd.io -ojson | jq -r '.spec.versions[].name'
v1alpha1
v1alpha2
```

**Comment by mcortinas** [comment]
hi! I'm sorry... but yes....let me share...
```
$kubectl get pods -n flux-system tf-controller-6c6c7567f-fhv9s -o yaml | grep image
    image: ghcr.io/weaveworks/tf-controller:main-43830881
    imagePullPolicy: IfNotPresent
    image: ghcr.io/weaveworks/tf-controller:main-43830881
    imageID: ghcr.io/weaveworks/tf-controller@sha256:e2f22e18a195414d4e95f5d80e230d16d63dfb6d303d3c36341425c00dbb4a3f
$kubectl get crd/terraforms.infra.contrib.fluxcd.io -ojson | jq -r '.spec.versions[].name'
v1alpha1
v1alpha2
$tfctl -n flux-system get; tfctl -n fluxcd-cloudflare get
NAMESPACE       NAME                    READY   MESSAGE                                                                                                                                                                                 PLAN PENDING    AGE    
flux-system     init-fluxcd-cloudflare  False   error running NewTerraform: rpc error: code = Unknown desc = no kind "Terraform" is registered for version "infra.contrib.fluxcd.io/v1alpha2" in scheme "pkg/runtime/scheme.go:100"     false           3 days
NAMESPACE               NAME                                            READY   MESSAGE                                                                                                                                                                                 PLAN PENDING    AGE      
fluxcd-cloudflare       account-liligo                                  False   error running NewTerraform: rpc error: code = Unknown desc = no kind "Terraform" is registered for version "infra.contrib.fluxcd.io/v1alpha2" in scheme "pkg/runtime/scheme.go:100"     false           19 hours
fluxcd-cloudflare       secret-fluxcd-cloudflare-cloudflareapitoken     False   error running NewTerraform: rpc error: code = Unknown desc = no kind "Terraform" is registered for version "infra.contrib.fluxcd.io/v1alpha2" in scheme "pkg/runtime/scheme.go:100"     false           3 days  
fluxcd-cloudflare       secret-fluxcd-cloudflare-datadogapikey          False   error running NewTerraform: rpc error: code = Unknown desc = no kind "Terraform" is registered for version "infra.contrib.fluxcd.io/v1alpha2" in scheme "pkg/runtime/scheme.go:100"     false           3 days  
fluxcd-cloudflare       workspace-fluxcd-cloudflare                     False   error running NewTerraform: rpc error: code = Unknown desc = no kind "Terraform" is registered for version "infra.contrib.fluxcd.io/v1alpha2" in scheme "pkg/runtime/scheme.go:100"     false           3 days 
```

**Comment by mcortinas** [comment]
finally the issue was in the runner image, i found an issue in my CI workflow, let me close the ticket and apologies for the time wasted

**Comment by chimisu** [comment]
Hi @mcortinas ,whats root issue?I met the same issue with yours.
