### ISSUE TITLE
move to fluxcd-community 

### ISSUE THREAD

**Issue by haarchri** [weaveworks/tf-controller#62]
is it an option to move the tf-controller with examples, helm-chart to https://github.com/fluxcd-community ?

**Comment by chanwit** [comment]
Yep, we're working on it with the Flux team. But the team will be busy pushing Flux to graduate, so our move is still less priority at the time. Please stay tuned.

**Comment by tomhuang12** [comment]
@haarchri The decision was made to move this project to the Weaveworks org.
