### ISSUE TITLE
Problem with chart 0.15.0 - `unknown flag: --allow-break-the-glass`

### ISSUE THREAD

**Issue by onedr0p** [weaveworks/tf-controller#635]
I just tried updating from 0.12.0 to 0.15.0 and I get the following error on the controller:

```
❯ k logs -n flux-system tf-controller-7d565d5898-hftjk
unknown flag: --allow-break-the-glass
```

**Comment by chanwit** [comment]
My apologies.

We are messing with the chart versioning right now in the process of matching them with app versions.

Please stay tuned. I'll keep you posted.

**Comment by chanwit** [comment]
@onedr0p could you try again with chart `0.15.0-rc.3` please?

**Comment by Twinki14** [comment]
I'm getting the same after todays `0.15.0` release
