### ISSUE TITLE
Should CRD's auto upgrade on installation of new version?

### ISSUE THREAD

**Issue by scott-david-walker** [weaveworks/tf-controller#638]
Question: on installing of a new release, does the controller (or anything else) upgrade the crds?

Thanks

**Comment by chanwit** [comment]
Yes it does if you're using HelmRelease to manage it.

**Comment by scott-david-walker** [comment]
We are, but the upgrade to the most recent rc release didn't update the crd in the cluster. 

Could you confirm the latest helm release version? (Or point me to the place I can find it?)

Cheers

**Comment by scott-david-walker** [comment]
I was being stupid, upgraded the image tag and not the helm version. Thanks for the quick reply @chanwit
