### ISSUE TITLE
Support writing outputs to ConfigMap

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#646]
There's a user requirement to support writing outputs not only to a Secret but also to ConfigMap so that users could be able to inspect the outputs without decoding.

There's a security concern around this as we would end up writing sensitive information to a ConfigMap unknowingly. To workaround this security concern, we would emit a warning to the event logs when a Terraform CR writes outputs to a ConfigMap.

========

**User Story:**

As a Terraform Controller user,
I'd like to have the option to write output values not only to a Secret but also to a ConfigMap,
so that I can inspect the outputs without decoding when the output is not sensitive.

**Acceptance Criteria:**
- [ ] Support writing outputs to ConfigMap in addition to Secret
- [ ] Emit a warning to the event logs when a Terraform CR writes outputs to a ConfigMap
- [ ] Provide documentation on how to use ConfigMap for outputs, including the potential security risks

**Comment by chanwit** [comment]
Security is a concern since sensitive data might be inadvertently exposed in ConfigMaps. Therefore, it's essential to implement a warning when using this feature, and to include necessary documentation highlighting potential risks.

**Comment by squaremo** [comment]
Honestly, I just wouldn't do this. It's not a great burden to decode secret data, and giving people the opportunity to accidentally put their sensitive data in ConfigMaps is not a good trade. I'm going to close this; reopen if you feel strongly in the other direction.
