### ISSUE TITLE
Post comment from Informer on new Plan Output

### ISSUE THREAD

**Issue by yitsushi** [weaveworks/tf-controller#664]
* When the informer detects a new Plan Output, find the corresponding PR (status/annotation)
* Create a new comment with the output.

**Comment by yiannistri** [comment]
It's not clear why we get this log line when running the branch-based planner with Tilt on main:
```
{"level":"info","ts":"2023-06-26T11:37:18.006Z","logger":"informer","msg":"previous object is not a Terraform object","version":"","sha":"","object":{"apiVersion":"infra.contrib.fluxcd.io/v1alpha2","kind":"Terraform","namespace":"flux-system","name":"helloworld-tf"}} 
```
as it looks like the object being logged is a Terraform object. It would be good to understand why this happens as part of this story.

Also, we should consider whether the above log is helpful during normal operation or whether it should appear as part of more verbose logging (debug).

**Comment by squaremo** [comment]
fmt.Printf("%s :: %#v\n", reflect.TypeOf(old), old)
