### ISSUE TITLE
[research] Evaluate potential testing strategies for end-to-end testing Branch-Based Planner

### ISSUE THREAD

**Issue by yitsushi** [weaveworks/tf-controller#665]
Evaluate potential testing strategies for end-to-end communication between GitHub, informer, polling server, and the K8s API server.

End result sought: an outline/document covering how to test, what tools we have to use to mock GitHub to test end-to-end flow

**Comment by yiannistri** [comment]
To run an end-to-end test for the branch planner we need the following:

1. An existing Git repository which contains a Terraform CR and related Terraform definitions
2. A GitHub token with permissions to create pull requests and post comments to issues.

The test execution would look this:
1. Create a kind cluster
2. Bootstrap flux and point it to the above Git repository
3. Install tf-controller with branch planner enabled
4. Wait for Terraform CR condition to be set to Ready
5. Create a branch with a patch which updates the Terraform definition and push it to GitHub. Then create a PR from the branch.
6. Wait for a specified time period
7. Check that a comment has been posted to the PR

**Comment by yitsushi** [comment]
> Create a branch with a patch which updates the Terraform definition and push it to GitHub. Then create a PR from the branch.

I wonder if we can just use one PR for everything and we don't have to create a new branch every time. The system checks configured repositories for PRs without corresponding TF object. On a new cluster it will be always the case.

**Comment by yiannistri** [comment]
@yitsushi It may be better to actually create a new PR and delete it after the test to keep things clean. Otherwise the test code needs to ensure that it checks the most recent comment from a long list of comments. Which is doable but makes troubleshooting the test a tiny bit more difficult.
