### ISSUE TITLE
 Can't delete resource terraform when tf runner pod has issue

### ISSUE THREAD

**Issue by chimisu** [weaveworks/tf-controller#666]
<img width="1103" alt="image" src="https://github.com/weaveworks/tf-controller/assets/12495369/84c9116a-b314-402e-b2a8-78508ef9e45d">

I created a terraform resource,but the tf runner has issue,I cant delete this resource,so what should i do?does this resource has timeout parameters?

========

**User Story**:

As a Kubernetes user using Terraform Controller,
I'd like to be able to delete Terraform resources even if tf runner pod has issues,
so that I can clean up and manage my resources effectively.

**Acceptance Criteria**:

- [ ] Able to delete Terraform resources regardless of tf runner pod status
- [ ] Provide timeout parameters for resource deletion with proper default values
- [ ] Proper error handling and messaging during resource deletion process
- [ ] Testing added
- [ ] We’ve created related user documentation

**Comment by chimisu** [comment]
tf-runner:v0.14.0
tf controller: v0.14.0
k8s: v1.23.3

**Comment by chanwit** [comment]
Hi @chimisu 

v0.14.0 is known to contain bug during the resource deletion process. Please use the new version from `docs/rc.yaml`? RC 5 contains many fixes regarding this.
