### ISSUE TITLE
Support customising state lock timeout

### ISSUE THREAD

**Issue by artem-nefedov** [weaveworks/tf-controller#680]
It would be useful to have a feature to customise state lock acquisition timeout, which is then should be passed to `-lock-timeout` option supported by various `terraform` commands:

* [-lock-timeout=DURATION](https://developer.hashicorp.com/terraform/cli/commands/plan#lock-timeout-duration) - Unless locking is disabled with -lock=false, instructs Terraform to retry acquiring a lock for a period of time before returning an error. The duration syntax is a number followed by a time unit letter, such as "3s" for three seconds.

Our use case is that we sometimes perform cluster blue/green upgrade by creating new cluster next to existing one instead of upgrading it in-place, and we have a period of time where both clusters have the same active Terraform resources (state is shared across both clusters in S3 bucket). This can result in same resource in both clusters trying to reconcile at the same time, which leads to one of them not being able to acquire state lock, even though it would be able to do that if it just waited a minute longer. This option would help avoid generating unnecessary errors in this scenario.

**Comment by Nalum** [comment]
@artem-nefedov we've recently merged the addition of `LockTimeout` to main for the [plan stage](https://github.com/weaveworks/tf-controller/pull/1087), would you also want to see this else where?

**Comment by artem-nefedov** [comment]
@Nalum I'm not sure I understand what "for the plan stage" actually means. For the scenario I described, it it most important to be able to customize lock for the first operation that requires lock acquisition, which (if I understand correctly) is "terraform init". Will the solution work like that?
