### ISSUE TITLE
Add ADR about polling, workflow, and responsibilities

### ISSUE THREAD

**Issue by yitsushi** [weaveworks/tf-controller#682]

**Comment by squaremo** [comment]
There's no rationale given here. Why are we doing this?

**Comment by chanwit** [comment]
ref: https://github.com/weaveworks/tf-controller/tree/main/rfcs/0001-polling-mechanism
maybe useful for the rationale part.

**Comment by yitsushi** [comment]
> There's no rationale given here. Why are we doing this?

ADRs are good if someone asks why we went this way, it is an easy way to look up/point to with a short and easy to understand summary (and not a 3 pages long full technical rfc/spec).
