### ISSUE TITLE
Auto-approve tests time out waiting for ready condition

### ISSUE THREAD

**Issue by squaremo** [weaveworks/tf-controller#716]
This happens a lot at present:
https://github.com/weaveworks/tf-controller/actions/runs/5393715792/jobs/9793842190

Looking at the debug logs, I see this message again and again:
```
error running Plan: rpc error: code = Internal desc = variable \"secret_subject\" was required but not supplied"
```

(first seen https://github.com/weaveworks/tf-controller/actions/runs/5393715792/jobs/9793842190#step:31:153, then repeated on backoff until the test times out after four minutes.) This suggests it's a bug, and not transient conditions.

**Comment by squaremo** [comment]
https://github.com/tf-controller/helloworld/commit/7353dc3abb7db80acb1afc915686490fbb8ac714 (earlier today) introduced a variable of the name `secret_subject` to main.tf in the helloworld repo; I'm guessing that's what caused this problem.

**Comment by chanwit** [comment]
Oh thank you so much for bringing this up, Michael.


I'll revert the commits and use another branch to test the secret subject
issue.

**Comment by chanwit** [comment]
Shall we close this one @squaremo ?

**Comment by squaremo** [comment]
Yep, thanks for reminding me :-)
Closed by https://github.com/tf-controller/helloworld/commit/7353dc3abb7db80acb1afc915686490fbb8ac714 being reverted.
