### ISSUE TITLE
0.15.0 - `unknown flag: --allow-break-the-glass`

### ISSUE THREAD

**Issue by Twinki14** [weaveworks/tf-controller#732]
After todays `0.15.0` release, upgrading from `0.12.0` I get `unknown flag: --allow-break-the-glass` in my logs

Same as https://github.com/weaveworks/tf-controller/issues/635

Downgrading back to `0.12.0` is my temporary solution.

**Comment by chanwit** [comment]
Could you please check values in your HelmRelease?

The controller and runner images must also be `v0.15.0`

**Comment by Twinki14** [comment]
Ahh I see, I did have both the image and runner image still on `v0.14.0`. My mistake!
