### ISSUE TITLE
[feature request] Terraform object compositions

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#734]
**User Story**

As a Kubernetes administrator or infrastructure operator,
I'd like to have Terraform object compositions functionality,
so that I can simplify Terraform CRs and accelerate the adoption of the Terraform Controller.

**Acceptance Criteria**

- [ ] The composition must not introduce extra custom resources. It must rely on the existing `Terraform` CR plus the new `TerraformConfig` CR.
- [ ] Support for defining composite Terraform CRs that encapsulate multiple underlying Terraform resources
- [ ] Ability to create, update, and delete composed Terraform CRs, reflecting the changes in the underlying Terraform resources
- [ ] The composition feature should be easy to use and integrate into existing Terraform configurations and workflows
- [ ] Clear documentation on how to define and use Terraform object compositions

**Comment by LappleApple** [comment]
Closing for now, can reopen in the future should it become more urgent.
