### ISSUE TITLE
readInputsFromSecrets fail in version 0.15.0

### ISSUE THREAD

**Issue by creatorKoo** [weaveworks/tf-controller#740]
It is critical bug!!

I using tf-controller spec to readInputsFromSecrets and writeOutputsToSecret

writeOutputsToSecret write type __type postfix.
(https://github.com/search?q=repo%3Aweaveworks%2Ftf-controller+%5C%22__type%5C%22&type=code)
but, readInputsFromSecrets read .type postfix. that's critical error for all system fail.
(https://github.com/search?q=repo%3Aweaveworks%2Ftf-controller+%5C%22.type%5C%22&type=code)

please fix this bug.

**Comment by chanwit** [comment]
@creatorKoo thank you for filing this. We'll prioritize this as a quick fix for v0.15.1 ASAP.

Sorry for any inconvenience caused by the bug.
