### ISSUE TITLE
Verify that it works with both https:// and ssh:// end points (should test with a repo bootstrapped via Flux)

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#776]

**Comment by yitsushi** [comment]
I think https://github.com/weaveworks/tf-controller/issues/779 verifies this. It's working, the branch based terraform object was created and it had a different issue.

From slack about #779 issue:
> chanwit: it does not get deleted on my machine

@chanwit : Can we close this one?

**Comment by chanwit** [comment]
Yes, sure.
