### ISSUE TITLE
Ability to set `priorityClass` on tf-runner pod

### ISSUE THREAD

**Issue by daniel-ciaglia** [weaveworks/tf-controller#786]
Hi,
we have the situation that we want to run around 100 Microservice TF stacks with ephemeral runners. Those stacks are not huge but still require CPU and Memory at `terraform init` and `terraform plan`.

As we have no influence on the schedule for these TF stacks, we would like to have a k8s quota on eg. number of pods in the `flux-system` namespace.
This would be doable but inflicts the risk that we put crucial pods back in the queue and render the Flux system unusable.

My thoughts went to `priorityClass` as a distinctor but I can not set the separate class as I lack access to the pod template. Hence my question: could you please somehow provide an interface to influence the pods deeper? Similar to the request on Resources and Limits (#526).

Greetings and thanks for this piece of software!

- https://kubernetes.io/docs/concepts/policy/resource-quotas/
- https://github.com/weaveworks/tf-controller/blob/19027da589d05e78165972807cbfa2553782a90a/controllers/tf_controller_runner.go#L40

========

**User Story:**

As a Kubernetes cluster administrator,
I'd like to be able to set a `priorityClass` on the tf-runner pod,
so that I can manage the scheduling and resource quotas of Terraform workloads efficiently.

**Acceptance Criteria:**

- [ ] Users can set a `priorityClass` for the tf-runner pod through the Terraform Controller configuration
- [ ] The `priorityClass` setting is properly applied to the tf-runner pod when scheduled
- [ ] The Terraform workloads adhere to the scheduling rules and resource quotas enforced by Kubernetes

**Comment by chanwit** [comment]
Thank you @daniel-ciaglia for reporting this.

We're thinking of allowing to customize of every field of the pod template and using the `mergo` library to override settings, instead of introducing the pod field one-by-one like what we did.

**Comment by LappleApple** [comment]
Relates to #261

**Comment by yiannistri** [comment]
Closed by #910
