### ISSUE TITLE
Rename "tf-controller-tf-controller-planner" to "tf-branch-planner" in the Deployment YAML

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#830]
rename "tf-controller-tf-controller-planner" to "tf-branch-planner" in HelmChart template

**Comment by LappleApple** [comment]
Not blocking anyone with current name.

**Comment by yitsushi** [comment]
will be resolved in https://github.com/weaveworks/tf-controller/pull/834

**Comment by chanwit** [comment]
Closed as completed by #834
