### ISSUE TITLE
SPIKE break-the-glass without pod exec but via mTLS gRPC

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#836]
This is possible, but we don't have evidence detailing a solution. We already have an mTLS gRPC server implemented on the runner side so we can do this.

Goal: show how it's done.

**Comment by chanwit** [comment]
We can design a gRPC call named "break-glass" that can be invoked only when the `--allow-break-the-glass` flag is enabled at the controller-level.

This "break-glass" gRPC call would take commands related to Terraform, such as:
- "terraform init"
- "terraform apply"
- "terraform outputs"
When these string commands are received, the "break-glass" gRPC call would execute the command within the container, in the directory where the Terraform files are extracted, capture both stdout and stderr, and then send the results back to the requester.

**Comment by yitsushi** [comment]
With that, the break-glass feature would lose some functionality, for example the ability to browse and examine the filesystem with the current tf files and we would have to implement every single command a user may want to use, for example `terraform force-unlock`, `terraform validate`. I don't know what functionality users want, I just point out we give the users this freedom now, and it will not be available after changing to this logic.

**Comment by chanwit** [comment]
I'm thinking of a file system dump capability too but we can discuss about it.

**Comment by yitsushi** [comment]
Note: It's on hold until we get some more information: https://github.com/weaveworks/weave-gitops-interlock/issues/467#issuecomment-1737496026

**Comment by LappleApple** [comment]
Closing due to change of plans.
