### ISSUE TITLE
Branch Planner documentation is 404

### ISSUE THREAD

**Issue by zerunhu** [weaveworks/tf-controller#838]
https://weaveworks.github.io/tf-controller/getting_started/

The link to '[Branch Planner documentation](https://github.com/weaveworks/tf-controller/blob/main/docs/branch_based_planner/getting-started.md).' in the document is inaccessible. please help fix it.

========

**User Story:**

As a user of Terraform Controller,
I'd like to have access to the Branch Planner documentation,
so that I can understand how to use the feature and provide feedback.

**Acceptance Criteria:**
- [ ] Fix the broken link in the Terraform Controller getting started guide.
- [ ] Ensure the Branch Planner documentation is publicly accessible.

**Comment by chanwit** [comment]
Hi @zerunhu 

The branch planner stuff hasn't been released yet.
We're working towards releasing it and would love to get feedback from you as well after releasing. Please stay tuned.

**Comment by chanwit** [comment]
It's released today.
