### ISSUE TITLE
Get started guide: "Helm install failed: context deadline exceeded"

### ISSUE THREAD

**Issue by jjo93sa** [weaveworks/tf-controller#858]
I've been trying to follow the [Get Started guide](https://docs.gitops.weave.works/docs/terraform/get-started-terraform/ ), but haven't been able to get it to work.

My first problem seems to be that the helm chart version in the controller [manifest](https://raw.githubusercontent.com/weaveworks/tf-controller/main/docs/release.yaml) downloaded in step 5 doesn't exist,  I was getting this error:

```
helmchart/flux-system-tf-controller                     False           False   chart pull error: failed to get chart version for remote reference: could not locate a version matching provided version string >=0.16.0-rc.3
```

Changing the version to `>=0.16.0-rc.2` got me a step further, but still something appears to be unhappy:

```
$ flux get helmreleases
NAME            REVISION        SUSPENDED       READY   MESSAGE                         
tf-controller                   False           False   Helm install failed: context deadline exceeded
```

And if I try a reconciliation:
```
$ flux reconcile helmrelease tf-controller
► annotating HelmRelease tf-controller in flux-system namespace
✔ HelmRelease annotated
◎ waiting for HelmRelease reconciliation
✗ client rate limiter Wait returned an error: context deadline exceeded
```
Am I doing something wrong? Could the guide, and manifest be updated to be consistent? 

Looking further down the guide, we come to the ["Quick Start"](https://docs.gitops.weave.works/docs/terraform/get-started-terraform/#quick-start). This presumably executes the Terraform contained in the hello world repository, but there's no discussion about what one should see, or how to determine that it has been properly & successfully executed.

**Comment by chanwit** [comment]
Hi @jjo93sa 
Thank you for reporting. I'm fixing the link in this PR: https://github.com/weaveworks/tf-controller/pull/860

**Comment by chanwit** [comment]
Please delete the HelmRelease object and try again.
We'll improve the docs shortly.

**Comment by jjo93sa** [comment]
Nothing seems to have changed, unfortunately. What I did:
1. Delete the HelmRelease object
2. Repeated step 5 of the quick start - curl the manifest 
3. Committed the new file to my repo

Results:
The `rc.3` chart version of the manifest still isn't found:

```
helmchart/flux-system-tf-controller     0.16.0-rc.2     False           False   chart pull error: failed to get chart version for remote reference: could not locate a version matching provided version string >=0.16.0-rc.3
```
 and changing to `>=0.16.0-rc.2` results in:

```
flux-system   tf-controller-7d99b94cf8-g64mq            0/1     ImagePullBackOff   0          3m59s
flux-system   tf-controller-7d99b94cf8-nq5zp            0/1     ImagePullBackOff   0          3m59s
flux-system   tf-controller-7d99b94cf8-zkrkn            0/1     ImagePullBackOff   0          3m59s
```

**Comment by chanwit** [comment]
v0.16.0-rc.3 has been released.
