### ISSUE TITLE
question: Hashicorp License changes

### ISSUE THREAD

**Issue by oliverbaehler** [weaveworks/tf-controller#861]
Hi there, just a quick question regarding the license change Hashicrop recently announced?

https://www.hashicorp.com/license-faq#What-is-considered-a-competitive-offering

Is the weave tf-controller impacted by this license change. Latest release of terraform under MPL seems to be version 1.5.5

**Comment by chanwit** [comment]
Hi @oliverbaehler

Here's the post from our CEO regarding this: https://www.weave.works/blog/statement-for-terraform-hashicorp-license-changes

**Comment by oliverbaehler** [comment]
Hi @chanwit, Thanks for the quick response! That clarifies things, thanks for the link 😊
