### ISSUE TITLE
Webhook behavior and structure

### ISSUE THREAD

**Issue by yehoshuadimarsky** [weaveworks/tf-controller#873]
Hi I see there's an option to configure webhooks to be invoked after tf plan but no documentation about it. I cannot get it to work, it sends the payload to my webhook but then fails with messages about invalid test expressions and error message templates. 
1. What are these fields used for
1. what should I put in them, and 
1. why are they causing failures if they are marked as optional?

https://weaveworks.github.io/tf-controller/References/terraform/#infra.contrib.fluxcd.io/v1alpha2.Webhook

Thanks 

========

**User Story:**

As a Terraform Controller user,
I'd like to understand how to configure and use webhooks properly,
so that I can invoke webhooks after tf plan and handle their responses.

**Acceptance Criteria:**

- [x] Documentation is updated to clarify webhook setup, usage, and the structure of the payload sent to webhooks
- [x] Explanation of the fields marked as optional, their purpose, and how to handle possible failures when using them
- [x] Examples provided in the documentation for webhook configuration

**Comment by chanwit** [comment]
New docs published: https://weaveworks.github.io/tf-controller/use_tf_controller/with_external_webhooks/

**Comment by yehoshuadimarsky** [comment]
This is great, thanks! One question - I am getting a giant dump of JSON into my webhook, even though I only made a small Terraform change, and set
```yaml
payloadType: PlanOnly
```
I see the values from here: https://github.com/weaveworks/tf-controller/blob/v0.15.1/api/v1alpha1/terraform_types.go#L276-L279

What exactly is this payload?

**Comment by chanwit** [comment]
It's the whole terraform plan of your resources in the JSON format.

**Comment by chanwit** [comment]
Completed by the new webhook docs.
