### ISSUE TITLE
Add flux "third party controllers" docs

### ISSUE THREAD

**Issue by kingdonb** [weaveworks/tf-controller#878]
This page is going away:

https://fluxcd.io/flux/cheatsheets/bootstrap/#enable-notifications-for-third-party-controllers

For reference the final content can be found here:

https://github.com/fluxcd/website/blob/1c2fa808008cd7ee0d0adfe9d2483d7db5320293/content/en/flux/cheatsheets/bootstrap.md#enable-notifications-for-third-party-controllers

The docs reorg in fluxcd/website#1573 moves most or all of the cheatsheet content into installation guides. I will help make sure this content does not get lost, let's put it in the TF-controller docs so folks can still find it.

**Comment by chanwit** [comment]
Yes please. Thank you so much @kingdonb for bringing this up.
