### ISSUE TITLE
[BUG] Not working on GKE Autopilot

### ISSUE THREAD

**Issue by hprotzek** [weaveworks/tf-controller#888]
Hi there, we are trying to use the `tf-controller` on a Google GKE Autopilot cluster. Unfortunately, we can't get it running. The runner pod starts and thennothing happens anymore. It seems that the controller can't get the connection to the runner pod due a restriction in the autopilot setup. (https://cloud.google.com/kubernetes-engine/docs/how-to/autopilot-hostport)

Any specific reason to use just a pod, without a service there?

**Comment by chanwit** [comment]
Being addressed by https://github.com/weaveworks/tf-controller/pull/886

**Comment by chanwit** [comment]
Completed by #886
