### ISSUE TITLE
Branch planner doesn't use changed variables in branch

### ISSUE THREAD

**Issue by cybercyst** [weaveworks/tf-controller#913]
**User stories**
- [ ] As a Terraform Controller user, I want to be able to receive a comment notifying me of all relevant changes I’ve made to my Terraform variables, so that I receive a complete set of information.
- [ ] As a Terraform Controller user, I want to be able to receive a comment notifying me of all relevant changes to my Terraform HCL, so that I receive a complete set of information.

**Acceptance Criteria** 
- After a Terraform plan run on all of my clusters, I want to see references in the comment to the changes I made in the branch in the PR.
- The produced output enables me to identify which TF generated the plan via a confirmation in the resulting plan, instead of saying “no changes.” 
- I don’t receive feedback about pods that aren’t affected by my change.
- Need to confirm that if I change a variable in main and push the change, that I will see a change in TF if I use TF runner without the branch planner. **(QQ: Does this already work?)**

According to this issue, the TF-controller branch planner does not support changing a variable to run the plan output in a PR.

There are 2 cases that result in changes to terraform managed objects:
1) A change to the Terraform HCL
2) A change to the Terraform variables

Modifying the HCL is supported by the branch planner.
Modifying the variables is not supported by the branch planner.

In order for the branch planner to be a complete feature, then both of these cases need to be supported by the planner.  
If this is not the case, then the usefulness of the branch planner is considerably reduced and this feature is not complete.

******Original comment from community member******
When changing the `vars` block in a `Terraform` resource in a branch, those changes are not reflected in ephemeral, PR-specific Terraform resource. This means that I might change some variables only and I get a comment in the PR saying No changes are detected.

**Comment by chanwit** [comment]
Oh you've filed it. Thank you so much @cybercyst

**Comment by cybercyst** [comment]
@chanwit thanks for everyone's hard work on it!

One more piece of context, we also use a base Terraform definition and then use Kustomize (from Flux) to change the variables and workspace for each environment

**Comment by chanwit** [comment]
Thank you for sharing that @cybercyst 

We unfortunately don't support that use case yet in the Branch Planner v0.16.0-rc.2. Will investigate more on how should we support the TerraformCR change in the Branch Planner. The current architecture doesn't allow that.

**Comment by LappleApple** [comment]
@chanwit questions that came up in my chat with @madAndroid about this issue:

- Instead of running a change for all the TF resources when I push a change to a branch, can I restrict a run to only the list of files that I’m pushing to Git/individual and related resources affected by the change? 
- Why would I want to see changes in other areas of my codebase?
- Could you not filter by changes by path within the Git repo, and then the changes are set in the PR to only surface the relevant files? Right now the diff surfaces many things that aren’t in the PR/related. Jenkins only includes what you expect.

**Comment by LappleApple** [comment]
Talking to @squaremo and we've distilled the request in this way:

**Scenario:** Person has a Git repo synced by Flux and there's a TF object. Flux applies the object to the cluster. TF-controller takes over and runs the program. User wants TF-controller to note a change to the Terraform definition, say "I see a change," and make a preview of that. 

**Problem:** This isn't what branch planner does now, and Flux doesn't do it, either. Flux doesn't go looking for branches saying, "I wonder if the user wants this to be applied." But if anything, it would be Flux's job to take care of this, not TF-Controller's. 

**Proposed resolution:** Closing this as out of scope.

cc @darrylweaver @madAndroid

**Comment by LappleApple** [comment]
Closing based on previous comment.
