### ISSUE TITLE
Branch planner breaks when branch has `/` in it

### ISSUE THREAD

**Issue by cybercyst** [weaveworks/tf-controller#915]
It might be convenient to slugify the branch name, as personally I use `/` in my branches. For example: `floomis/feat/really-cool-thing` or `floomis/chore/ran-the-linter`

**Comment by chanwit** [comment]
Thank you for trying Branch Planner @cybercyst 

Yep, it's an obvious bug. Will take a look at it shortly.

**Comment by navpreet-securitas** [comment]
same is correct if branch contains _
