### ISSUE TITLE
Document --allow-cross-namespace-refs

### ISSUE THREAD

**Issue by squaremo** [weaveworks/tf-controller#956]
- [x] explain how cross-namespace refs are handled, and the flags --allow-cross-namespace-refs and --no-cross-namespace-refs
 - [x] document the value in the Helm chart README

**Comment by squaremo** [comment]
@chanwit I'm not sure where is an appropriate place in the documentation for this first one:
> explain how cross-namespace refs are handled, and the flags --allow-cross-namespace-refs and --no-cross-namespace-refs
Where do you think would work?

**Comment by chanwit** [comment]
Maybe under the How-To section?
