### ISSUE TITLE
The doc on the getting started page referencing to a version that doesn't exist 

### ISSUE THREAD

**Issue by YoucefGuichi** [weaveworks/tf-controller#985]
Just a quick remark: The following yaml referencing to `version: '>=0.16.0-rc.3'` which doesn't exist! and it failed when installing it.
https://weaveworks.github.io/tf-controller/getting_started/#:~:text=kubectl%20apply%20%2Df%20https%3A//raw.githubusercontent.com/weaveworks/tf%2Dcontroller/main/docs/release.yaml

**Comment by chanwit** [comment]
We're testing the release pipeline of RC3 for now. Please change it to RC2 in the mean time.
Sorry for inconvenience.

**Comment by chanwit** [comment]
RC3 has been released.
